- platform: template
  sensors:
    days_in_month:
      entity_id: now.month
      value_template: >
        {% set days = {
        1 : 31,
        2 : 28,
        3 : 31,
        4 : 30,
        5 : 31,
        6 : 30,
        7 : 31,
        8 : 31,
        9 : 30,
        10 : 31,
        11 : 30,
        12 : 31
        } %}
        {{days[now().month]}}