- platform: template
  sensors:
    t1_battery_level:
      value_template: "{{ states.sensor.temperature_158d0002271609.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: sensor.temperature_158d0002271609
    t2_battery_level:
      value_template: "{{ states.sensor.temperature_158d0001f23cbe.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: sensor.temperature_158d0001f23cbe
    t3_battery_level:
      value_template: "{{ states.sensor.temperature_158d00022c7cf2.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: sensor.temperature_158d00022c7cf2
    t4_battery_level:
      value_template: "{{ states.sensor.temperature_158d000234816a.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: sensor.temperature_158d000234816a
    t5_battery_level:
      value_template: "{{ states.sensor.temperature_158d0002323783.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: sensor.temperature_158d0002323783
    doorbell_switch_battery_level:
      value_template: "{{ states.binary_sensor.switch_158d00021350ee.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: binary_sensor.switch_158d00021350ee
    livingroom_light_switch_battery_level:
      value_template: "{{ states.binary_sensor.switch_158d0002136276.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: binary_sensor.switch_158d0002136276
    motion1_battery_level:
      value_template: "{{ states.binary_sensor.motion_sensor_158d0001e52779.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: binary_sensor.motion_sensor_158d0001e52779
    motion2_battery_level:
      value_template: "{{ states.binary_sensor.motion_sensor_158d0001fa3dc0.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: binary_sensor.motion_sensor_158d0001fa3dc0
    door_sensor_battery_level:
      value_template: "{{ states.binary_sensor.door_window_sensor_158d00024367c8.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
    sw1_standalone_battery_level:
      entity_id: binary_sensor.wall_switch_both_158d00026b96c1
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.wall_switch_both_158d00026b96c1.attributes.battery_level | float }}"
    cube_battery_level:
      value_template: "{{ states.binary_sensor.cube_158d00028776ae.attributes.battery_level | float }}"
      unit_of_measurement: "%"
      entity_id: binary_sensor.cube_158d00028776ae
    power_strip_1_load_power:
      value_template: "{{ states.switch.power_strip_1.attributes.load_power | float }}"
      unit_of_measurement: "Wh"
      entity_id: switch.power_strip_1
    power_strip_2_load_power:
      value_template: "{{ states.switch.power_strip_2.attributes.load_power | float }}"
      unit_of_measurement: "Wh"
      entity_id: switch.power_strip_2
    power_strip_3_load_power:
      value_template: "{{ states.switch.power_strip_3.attributes.load_power | float }}"
      unit_of_measurement: "Wh"
      entity_id: switch.power_strip_3
    power_strip_4_load_power:
      value_template: "{{ states.switch.power_strip_4.attributes.load_power | float }}"
      unit_of_measurement: "Wh"
      entity_id: switch.power_strip_4
    dima_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_111683533988744565132', 'home') }}"
      entity_id: device_tracker.google_maps_111683533988744565132
    alyona_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_115914092349482836896', 'home') }}"
      entity_id: device_tracker.google_maps_115914092349482836896
    yury_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_117454969161947422882', 'home') }}"
      entity_id: device_tracker.google_maps_117454969161947422882
    parents_are_home:
      value_template: "{{ is_state('dima_is_home', 'true') or is_state('alyona_is_home', 'true') }}"
      entity_id:
      - device_tracker.google_maps_111683533988744565132
      - device_tracker.google_maps_115914092349482836896
    livingroom_ambient_flow_is_on:
      value_template: "{{ is_state('input_boolean.livingroom_torch_use', 'on') or is_state('input_boolean.livingroom_corner_use', 'on') }}"
      entity_id:
      - input_boolean.livingroom_torch_use
      - input_boolean.livingroom_corner_use
    is_workday:
      value_template: "{{ now().weekday() >= 0 and now().weekday() <= 5 }}"
      entity_id: now.weekday
