- platform: template
  sensors:
#BATTERIES
#env sensors
    t1_battery_level:
      value_template: "{{ states.sensor.temperature_158d0002271609.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d0002271609
      friendly_name: Yuri room climate sensor
    t2_battery_level:
      value_template: "{{ states.sensor.temperature_158d0001f23cbe.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d0001f23cbe
      friendly_name: Bedroom climate sensor
    t3_battery_level:
      value_template: "{{ states.sensor.temperature_158d00022c7cf2.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d00022c7cf2
      friendly_name: Park climate sensor
    t5_battery_level:
      value_template: "{{ states.sensor.temperature_158d0002323783.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d0002323783
      friendly_name: Yard climate sensor
    t6_battery_level:
      value_template: "{{ states.sensor.temperature_158d00032308dd.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d00032308dd
      friendly_name: Kitchen climate sensor

#buttons
    doorbell_button_battery_level:
      value_template: "{{ states.binary_sensor.switch_158d00021350ee.attributes.battery_level | float }}"
      entity_id: binary_sensor.switch_158d00021350ee
      friendly_name: Doorbell
#LOAD POWERS
    power_strip_1_load_power:
      value_template: "{{ states.switch.power_strip_1.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_1
    power_strip_2_load_power:
      value_template: "{{ states.switch.power_strip_2.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_2
    power_strip_3_load_power:
      value_template: "{{ states.switch.power_strip_3.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_3
    power_strip_4_load_power:
      value_template: "{{ states.switch.power_strip_4.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_4
    power_strip_5_load_power:
      value_template: "{{ states.switch.power_strip_5.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_5
#LOCATION
    dima_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_111683533988744565132', 'home') }}"
      entity_id: device_tracker.google_maps_111683533988744565132
    alyona_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_115914092349482836896', 'home') }}"
      entity_id: device_tracker.google_maps_115914092349482836896
    yury_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_117454969161947422882', 'home') }}"
      entity_id: device_tracker.google_maps_117454969161947422882
#STATE_CH
    state_change_door_ago_min:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_door.state, '%Y%m%d%H%M%S').astimezone()).seconds / 60) | round(0) }}"
      entity_id: binary_sensor.0x00158d00024367c8_contact
      unit_of_measurement: "minutes"
    state_change_door_ago_sec:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_door.state, '%Y%m%d%H%M%S').astimezone()).seconds) | round(0) }}"
      entity_id: binary_sensor.0x00158d00024367c8_contact
      unit_of_measurement: "sec"
#STATE_CH_MANUAL
    state_change_dima_ago:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_dima.state, '%Y%m%d%H%M%S').astimezone()).seconds / 60) | round(0) }}"
      unit_of_measurement: "minutes"
    state_change_alyona_ago:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_alyona.state, '%Y%m%d%H%M%S').astimezone()).seconds / 60) | round(0) }}"
      unit_of_measurement: "minutes"
#ABOX
    androidbox_app:
      value_template: "{{ states.media_player.androidbox.attributes.app_id.split('.')[-1] }}"
      entity_id: media_player.androidbox
    androidbox_app_full:
      value_template: "{{ states.media_player.androidbox.attributes.app_id }}"
      entity_id: media_player.androidbox
#STATE_CH_TIME
    now_hm:
      value_template: "{{ now().strftime('%H:%M') }}"
      entity_id: sensor.time
    now_ymdhms:
      value_template: "{{ now().strftime('%Y%m%d%H%M%S') }}"
      entity_id: sensor.time
    now_ymd:
      value_template: "{{ now().strftime('%Y-%m-%d') }}"
      entity_id: sensor.time
#RPI
    rpi:
      value_template: "{{states.sensor.processor_use.state_with_unit}} / {{states.sensor.memory_use_percent.state_with_unit}} / {{states.sensor.temperature.state_with_unit}}"
      entity_id:
        - sensor.processor_use
        - sensor.memory_use_percent
        - sensor.temperature

