- platform: template
  sensors:
#LOAD POWERS
    power_strip_1_load_power:
      value_template: "{{ states['switch.power_strip_1'].attributes.load_power | float }}"
      unit_of_measurement: "W"
    power_strip_2_load_power:
      value_template: "{{ states['switch.power_strip_2'].attributes.load_power | float }}"
      unit_of_measurement: "W"
    power_strip_3_load_power:
      value_template: "{{ states['switch.power_strip_3'].attributes.load_power | float }}"
      unit_of_measurement: "W"
    power_strip_4_load_power:
      value_template: "{{ states['switch.power_strip_4'].attributes.load_power | float }}"
      unit_of_measurement: "W"
    power_strip_5_load_power:
      value_template: "{{ states['switch.power_strip_5'].attributes.load_power | float }}"
      unit_of_measurement: "W"
#ABOX
    androidbox_app:
      value_template: "{{ states['media_player.androidbox'].attributes.app_id.split('.')[-1] }}"
    androidbox_app_full:
      value_template: "{{ states['media_player.androidbox'].attributes.app_id }}"
#STATE_CH_TIME
    now_hm:
      value_template: >
        {{ now().strftime('%H:%M') }}
    now_ymd:
      value_template: >
        {{ now().strftime('%Y-%m-%d') }}

#RPI
    rpi:
      value_template: "{{states['sensor.processor_use'].state_with_unit}} / {{states['sensor.memory_use_percent'].state_with_unit}} / {{states['sensor.temperature'].state_with_unit}}"
#SUN
    zenith:
      value_template: "{{ states['input_number.zenith'].state | float }}"
      unit_of_measurement: "°"
    nadir:
      value_template: "{{ states['input_number.nadir'].state | float }}"
      unit_of_measurement: "°"