- platform: template
  sensors:
#LOAD POWERS
    power_strip_1_load_power:
      value_template: "{{ state_attr('switch.power_strip_1', 'load_power') | float }}"
      unit_of_measurement: "W"
    power_strip_2_load_power:
      value_template: "{{ state_attr('switch.power_strip_2', 'load_power') | float }}"
      unit_of_measurement: "W"
    power_strip_3_load_power:
      value_template: "{{ state_attr('switch.power_strip_3', 'load_power') | float }}"
      unit_of_measurement: "W"
    power_strip_4_load_power:
      value_template: "{{ state_attr('switch.power_strip_4', 'load_power') | float }}"
      unit_of_measurement: "W"
    power_strip_5_load_power:
      value_template: "{{ state_attr('switch.power_strip_5', 'load_power') | float }}"
      unit_of_measurement: "W"
#ABOX
    abox_app:
      value_template: "{{ states('sensor.abox_app_full').split('.')[-1] }}"
    abox_app_full:
      value_template: "{{ state_attr('media_player.androidbox', 'app_id') }}"
    abox_temp:
      value_template: "{{ ((state_attr('media_player.androidbox', 'adb_response') | default('0') | float) / 1000) | float }}"

#HYPE
    hyperion_effect:
      value_template: "{{ state_attr('light.hyperion', 'effect') }}"

#TIME
    now_hm:
      value_template: "{{ now().strftime('%H:%M') }}"
    now_ymd:
      value_template: "{{ now().strftime('%Y-%m-%d') }}"
    system_uptime:
      value_template: "{{ ((as_timestamp(now()) - as_timestamp(states('sensor.uptime'))) | int / 3600) | round(2) }}"
    door_duration_sec:
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states('input_datetime.door'))) | int }}"
    door_duration_min:
      value_template: "{{ ((as_timestamp(now()) - as_timestamp(states('input_datetime.door')))) | int // 60 }}"
    dima_duration_min:
      value_template: "{{ ((as_timestamp(now()) - as_timestamp(states('input_datetime.dima')))) | int // 60 }}"

#RPI
    rpi:
      value_template: "{{states['sensor.processor_use'].state_with_unit}} / {{states['sensor.memory_use_percent'].state_with_unit}} / {{states['sensor.temperature'].state_with_unit}}"
#SUN
    zenith:
      value_template: "{{ states('input_number.zenith') | float }}"
      unit_of_measurement: "°C"
    nadir:
      value_template: "{{ states('input_number.nadir') | float }}"
      unit_of_measurement: "°C"
#SCALE
    dmitry_bmi:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'bmi') }}"
    dmitry_body_type:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'body_type') }}"
    dmitry_muscle_mass:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'muscle_mass') }}"
    dmitry_bone_mass:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'bone_mass') }}"
    dmitry_visceral_fat:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'visceral_fat') }}"
    dmitry_body_fat:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'body_fat') }}"
    dmitry_water:
      value_template: "{{ state_attr('sensor.dmitry_weight', 'water') }}"
    
    yury_interactive_mins:
      value_template: "{{ (states('sensor.yury_interactive') | float * 60) | int }}"