- platform: template
  sensors:
    t1_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.sensor.temperature_158d0002271609.attributes.battery_level | float}}"
    t2_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.sensor.temperature_158d0001f23cbe.attributes.battery_level | float}}"
    t3_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.sensor.temperature_158d00022c7cf2.attributes.battery_level | float}}"
    t4_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.sensor.temperature_158d000234816a.attributes.battery_level | float}}"
    doorbell_switch_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.switch_158d00021350ee.attributes.battery_level | float}}"
    livingroom_light_switch_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.switch_158d0002136276.attributes.battery_level | float}}"
    motion1_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.motion_sensor_158d0001e52779.attributes.battery_level | float}}"
    motion2_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.motion_sensor_158d0001fa3dc0.attributes.battery_level | float}}"
    door_sensor_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.door_window_sensor_158d00024367c8.attributes.battery_level | float}}"
    sw1_standalone_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.wall_switch_both_158d00026b96c1.attributes.battery_level | float}}"
    cube_battery_level:
      unit_of_measurement: "%"
      value_template: "{{states.binary_sensor.cube_158d00028776ae.attributes.battery_level | float}}"
    power_strip_1_load_power:
      unit_of_measurement: "Wh"
      value_template: "{{ states.switch.power_strip_1.attributes.load_power | float }}"
    power_strip_2_load_power:
      unit_of_measurement: "Wh"
      value_template: "{{ states.switch.power_strip_2.attributes.load_power | float }}"
    power_strip_3_load_power:
      unit_of_measurement: "Wh"
      value_template: "{{ states.switch.power_strip_3.attributes.load_power | float }}"
    power_strip_4_load_power:
      unit_of_measurement: "Wh"
      value_template: "{{ states.switch.power_strip_4.attributes.load_power | float }}"
    cube_action:
      value_template: "{{ states.binary_sensor.cube_158d00028776ae.attributes.last_action }}"