- platform: template
  sensors:
#BATTERIES
#env sensors
    t1_battery_level:
      value_template: "{{ states.sensor.temperature_158d0002271609.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d0002271609
      friendly_name: Yuri room climate sensor
    t2_battery_level:
      value_template: "{{ states.sensor.temperature_158d0001f23cbe.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d0001f23cbe
      friendly_name: Bedroom climate sensor
    t3_battery_level:
      value_template: "{{ states.sensor.temperature_158d00022c7cf2.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d00022c7cf2
      friendly_name: Outside climate sensor
    t4_battery_level:
      value_template: "{{ states.sensor.temperature_158d000234816a.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d000234816a
      friendly_name: Living room climate sensor
    t5_battery_level:
      value_template: "{{ states.sensor.temperature_158d0002323783.attributes.battery_level | float }}"
      entity_id: sensor.temperature_158d0002323783
      friendly_name: Kitchen climate sensor
#buttons
    doorbell_button_battery_level:
      value_template: "{{ states.binary_sensor.switch_158d00021350ee.attributes.battery_level | float }}"
      entity_id: binary_sensor.switch_158d00021350ee
      friendly_name: Doorbell
    livingroom_light_button_battery_level:
      value_template: "{{ states.binary_sensor.switch_158d0002136276.attributes.battery_level | float }}"
      entity_id: binary_sensor.switch_158d0002136276
      friendly_name: Living room light button
    pass_button_battery_level:
      value_template: "{{ states.binary_sensor.switch_158d00021329e3.attributes.battery_level | float }}"
      entity_id: binary_sensor.switch_158d00021329e3
      friendly_name: Entrance button
#motion
    motion1_battery_level:
      value_template: "{{ states.binary_sensor.motion_sensor_158d0001e52779.attributes.battery_level | float }}"
      entity_id: binary_sensor.motion_sensor_158d0001e52779
      friendly_name: Bathroom motion sensor
    motion2_battery_level:
      value_template: "{{ states.binary_sensor.motion_sensor_158d0001fa3dc0.attributes.battery_level | float }}"
      entity_id: binary_sensor.motion_sensor_158d0001fa3dc0
      friendly_name: Living room motion sensor
    motion3_battery_level:
      value_template: "{{ states.binary_sensor.motion_sensor_158d0002d43d7d.attributes.battery_level | float }}"
      entity_id: binary_sensor.motion_sensor_158d0002d43d7d
      friendly_name: Living room motion sensor
#misc
    door_sensor_battery_level:
      value_template: "{{ states.binary_sensor.door_window_sensor_158d00024367c8.attributes.battery_level | float }}"
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      friendly_name: Entrance door sensor
    sw1_standalone_battery_level:
      entity_id: binary_sensor.wall_switch_both_158d00026b96c1
      value_template: "{{ states.binary_sensor.wall_switch_both_158d00026b96c1.attributes.battery_level | float }}"
      friendly_name: Standalone switch 1
    cube_battery_level:
      value_template: "{{ states.binary_sensor.cube_158d00028776ae.attributes.battery_level | float }}"
      entity_id: binary_sensor.cube_158d00028776ae
      friendly_name: Cube
#LOAD POWERS
    power_strip_1_load_power:
      value_template: "{{ states.switch.power_strip_1.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_1
    power_strip_2_load_power:
      value_template: "{{ states.switch.power_strip_2.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_2
    power_strip_3_load_power:
      value_template: "{{ states.switch.power_strip_3.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_3
    power_strip_4_load_power:
      value_template: "{{ states.switch.power_strip_4.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_4
    power_strip_5_load_power:
      value_template: "{{ states.switch.power_strip_5.attributes.load_power | float }}"
      unit_of_measurement: "W"
      entity_id: switch.power_strip_5
#LOCATION
    dima_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_111683533988744565132', 'home') }}"
      entity_id: device_tracker.google_maps_111683533988744565132
    alyona_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_115914092349482836896', 'home') }}"
      entity_id: device_tracker.google_maps_115914092349482836896
    yury_is_home:
      value_template: "{{ is_state('device_tracker.google_maps_117454969161947422882', 'home') }}"
      entity_id: device_tracker.google_maps_117454969161947422882
#STATE_CH
    state_change_door_ago_min:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_door.state, '%Y%m%d%H%M%S').astimezone()).seconds / 60) | round(0)}} min"
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
    state_change_door_ago_sec:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_door.state, '%Y%m%d%H%M%S').astimezone()).seconds) | round(0)}} sec"
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
#STATE_CH_MANUAL
    state_change_dima_ago:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_dima.state, '%Y%m%d%H%M%S').astimezone()).seconds / 60) | round(0)}} min"
    state_change_alyona_ago:
      value_template: "{{ ((now() - strptime(states.input_text.state_change_alyona.state, '%Y%m%d%H%M%S').astimezone()).seconds / 60) | round(0)}} min"
#MISC
    livingroom_ambient_flow_is_on:
      value_template: "{{ is_state('input_boolean.livingroom_torch_use', 'on') or is_state('input_boolean.livingroom_corner_use', 'on') }}"
      entity_id:
      - input_boolean.livingroom_torch_use
      - input_boolean.livingroom_corner_use
    computer_on_today_minutes:
      value_template: "{{((states.sensor.computer_on_today.state | float) * 60) | int}}"
      entity_id: sensor.computer_on_today
    laptop_on_today_minutes:
      value_template: "{{((states.sensor.laptop_on_today.state | float) * 60) | int}}"
      entity_id: sensor.laptop_on_today
    now_hm:
      value_template: "{{ now().strftime('%H:%M') }}"
      entity_id: sensor.time
    now_ymdhms:
      value_template: "{{ now().strftime('%Y%m%d%H%M%S') }}"
      entity_id: sensor.time
    abox_app:
      value_template: "{{ states.media_player.abox.attributes.app_id.package.split('.')[-1] }}"
      entity_id: media_player.abox

    next_dusk:
      value_template: "{{ states.sun.sun.attributes.next_dusk.split('T')[1][0:5] }}"
      entity_id: sun.sun
    next_dawn:
      value_template: "{{ states.sun.sun.attributes.next_dawn.split('T')[1][0:5] }}"
      entity_id: sun.sun
