- platform: ping
  name: "ping_computer"
  host: 192.168.1.101
  count: 2
  scan_interval: 30

- platform: ping
  name: "ping_laptop"
  host: 192.168.1.102
  count: 2
  scan_interval: 33

- platform: ping
  name: "ping_abox"
  host: 192.168.1.21
  count: 2
  scan_interval: 36

- platform: ping
  name: "ping_rpi3"
  host: 192.168.1.11
  count: 2
  scan_interval: 44