- platform: rest
  name: "hyperion_v4l"
  resource: http://192.168.1.11:8090/json-rpc
  method: POST
  # content_type: "application/json"
  payload: >
    {
        "command":"serverinfo",
        "tan":1
    }
  value_template: "{{ value_json.info.components[6].enabled }}"
  scan_interval: 60

- platform: rest
  name: "hyperion_leddevice"
  resource: http://192.168.1.11:8090/json-rpc
  method: POST
  # content_type: "application/json"
  payload: >
    {
        "command":"serverinfo",
        "tan":1
    }
  value_template: "{{ value_json.info.components[7].enabled }}"
  scan_interval: 60