- platform: template
  sensors:
    is_holiday:
      value_template: >
        {% set x = states('sensor.date') %}
        {% if 
          states('sensor.date').endswith('01-01') or
          states('sensor.date').endswith('05-01') or
          states('sensor.date').endswith('05-04') or
          states('sensor.date').endswith('06-23') or
          states('sensor.date').endswith('06-24') or
          states('sensor.date').endswith('11-18') or
          states('sensor.date').endswith('12-24') or
          states('sensor.date').endswith('12-25') or
          states('sensor.date').endswith('12-26') or
          states('sensor.date').endswith('12-31')
        %}
          true
        {% elif 
          states('sensor.date').endswith('2020-04-10') or
          states('sensor.date').endswith('2020-04-13')
        %}
          true
        {% else %}
          false
        {% endif %}

    is_workday:
      value_template: >
        {% if is_state('binary_sensor.is_holiday', 'on') %}
          false
        {% else %}
          {{ now().weekday() >= 0 and now().weekday() <= 4 }}
        {% endif %}

    is_morning_activity:
      value_template: >
        {{
          is_state('binary_sensor.is_workday', 'on')
          and
          is_state('input_boolean.is_vacation', 'off')
          and
          is_state('input_boolean.is_school', 'on')
        }}

    is_backup_day:
      value_template: "{{ now().weekday() == 1 or now().weekday() == 3 or now().weekday() == 6 }}"

    is_month_last_day:
      value_template: "{{ (as_timestamp(now()) + 86400) | timestamp_custom('%d', true) == 01 }}"

    is_hallway_ceiling_high_brightness:
      value_template: "{{ (state_attr('light.hallway_ceiling', 'brightness') | int) > 240 }}"

    is_yury_phone_overdue:
      value_template: "{{ (states('sensor.yury_interactive') | float * 60) >= states('input_number.yury_phone_allowed') | float }}"

    ping_tv:
      value_template: "{{ states('sensor.power_strip_4_load_power') | float > 70 }}"

    people_home:
      value_template: >
        {{
        is_state('light.big_torch', 'on') or
        is_state('light.corner_lamp', 'on') or
        is_state('binary_sensor.ping_computer', 'on') or
        is_state('binary_sensor.ping_laptop', 'on') or
        is_state('binary_sensor.ping_tv', 'on') or
        is_state('media_player.kitchen_display', 'playing') or
        is_state('media_player.loud_speaker', 'playing') or
        is_state('media_player.yury_speaker', 'playing')
        }}

    androidbox_in_use:
      value_template: >
        {{
        not(
        is_state('sensor.androidbox_app', 'launcher') or
        is_state('sensor.androidbox_app', 'unknown')
        )
        }}

    some_casting:
      value_template: >
        {{
        (
        is_state('media_player.loud_speaker', 'playing') or
        is_state('media_player.black_speaker', 'playing') or
        is_state('media_player.yury_speaker', 'playing') or
        is_state('media_player.kitchen_display', 'playing') or
        is_state('media_player.surround', 'playing') or
        is_state('media_player.speakers', 'playing')
        )
        }}

    sun_is_rising:
      value_template: "{{ state_attr('sun.sun', 'rising') }}"