- platform: template
  sensors:
    is_workday:
      value_template: >
        {% if is_state('input_boolean.is_vacation', 'on') %}
          false
        {% else %}
          {{ now().weekday() >= 0 and now().weekday() <= 4 }}
        {% endif %}
      entity_id: now.weekday

    ping_tv:
      value_template: "{{ states.sensor.power_strip_4_load_power.state | float > 80 }}"
      entity_id: sensor.power_strip_4_load_power

    people_home:
      value_template: >
        {{
        is_state('light.big_torch', 'on') or
        is_state('light.corner_lamp', 'on') or
        is_state('binary_sensor.ping_computer', 'on') or
        is_state('binary_sensor.ping_laptop', 'on') or
        is_state('binary_sensor.ping_tv', 'on') or
        is_state('media_player.kitchen_display', 'playing') or
        is_state('media_player.loud_speaker', 'playing') or
        is_state('media_player.yury_speaker', 'playing')
        }}
      entity_id:
        - light.big_torch
        - light.corner_lamp
        - binary_sensor.ping_computer
        - binary_sensor.ping_laptop
        - binary_sensor.ping_tv
        - media_player.kitchen_display
        - media_player.loud_speaker
        - media_player.yury_speaker

    ping_abox:
      value_template: >
        {{
        not(
        is_state('sensor.abox_app', 'launcher') or
        is_state('sensor.abox_app', 'unknown')
        )
        }}
      entity_id:
        - sensor.abox_app
        - media_player.abox