- alias: "autoupdate_youtube_media_id"
  trigger:
    - platform: state
      entity_id: input_text.youtube_url
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.youtube_id
        value: "{{ states('input_text.youtube_url').split('/')[-1] | regex_replace('watch\\?v=', '') | regex_replace('&t=.*', '') }}"