- alias: "autoupdate_radio_cast_entity"
  trigger:
    - platform: state
      entity_id: input_select.radio_cast
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.radio_cast
        value: >
          {% if is_state("input_select.radio_cast", "Kitchen speaker") %} media_player.kitchen_display
          {% elif is_state("input_select.radio_cast", "Loud speaker") %} media_player.loud_speaker
          {% elif is_state("input_select.radio_cast", "Yury speaker") %} media_player.yury_speaker
          {% elif is_state("input_select.radio_cast", "Black speaker") %} media_player.black_speaker
          {% elif is_state("input_select.radio_cast", "Speakers") %} media_player.speakers
          {% elif is_state("input_select.radio_cast", "Surround") %} media_player.surround
          {% endif %}

- alias: "autoupdate_youtube_media_id"
  trigger:
    - platform: state
      entity_id: input_text.youtube_url
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.youtube_id
        value: "{{ states('input_text.youtube_url').split('/')[-1] | regex_replace('watch\\?v=', '') | regex_replace('&t=.*', '') }}"