- alias: "computer_limit_reached"
  trigger:
    - platform: time_pattern
      seconds: "/300"
  condition:
    - condition: state
      entity_id: input_boolean.computer_today_limit
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
    - condition: template
      value_template: "{{ states.sensor.computer_on_today_minutes.state | int >= states.input_number.computer_today_allowed.state | int}}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
          - !secret tg_chat_dima
          - !secret tg_chat_alyona
        message: "{{ now().strftime('%H:%M') }} \U0001F61E Computer limit reached. Turning off"
        inline_keyboard:
          - "\U000023F1 Extend 30 min:/rmt_computer_limit_extend, \U0001F6A8 Disable limit:/rmt_computer_limit_disable"
          - "\U0000267B Dismiss:/dismiss"
    - service:  script.rmt_computer_sleep

- alias: "computer_limit_warning"
  trigger:
    - platform: time_pattern
      minutes: "/5"
      seconds: 00
  condition:
    - condition: state
      entity_id: input_boolean.computer_today_limit
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
    - condition: template
      value_template: "{{ (states.input_number.computer_today_allowed.state | int - states.sensor.computer_on_today_minutes.state | int) < 30}}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
          - !secret tg_chat_dima
          - !secret tg_chat_alyona
        message: "{{ now().strftime('%H:%M') }} \U0001F914 Computer used {{ states.sensor.computer_on_today_minutes.state | int }}/{{states.input_number.computer_today_allowed.state | int}} minutes"
        inline_keyboard:
          - "\U000023F1 Extend 30 min:/rmt_computer_limit_extend, \U0001F6A8 Disable limit:/rmt_computer_limit_disable"
          - "\U0000267B Dismiss:/dismiss"
