- alias: "computer_limit_reached"
  trigger:
    - platform: time_pattern
      seconds: "/300"
  condition:
    - condition: state
      entity_id: input_boolean.computer_today_limit
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
    - condition: template
      value_template: "{{ states.sensor.computer_on_today_min.state | int >= states.input_number.computer_today_allowed.state | int }}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
          - !secret tg_chat_dima
          - !secret tg_chat_alyona
        message: "{{ states.sensor.now_hm.state }} \U0001F61E Computer limit reached. Turning off"
        inline_keyboard:
          - "\U000023F1 Extend 30 min:/rmt_computer_limit_extend, \U0001F6A8 Disable limit:/rmt_computer_limit_disable"
          - "\U0000267B Dismiss:/dismiss"
    - service:  script.rmt_computer_sleep

- alias: "computer_limit_warning"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: input_boolean.computer_today_limit
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
    - condition: template
      value_template: "{{ (states.input_number.computer_today_allowed.state | int - states.sensor.computer_on_today_min.state | int) < 30 }}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
          - !secret tg_chat_dima
          - !secret tg_chat_alyona
        message: "{{ states.sensor.now_hm.state }} \U0001F914 Computer used {{ states.sensor.computer_on_today_min.state | int }}/{{ states.input_number.computer_today_allowed.state | int }} minutes"
        inline_keyboard:
          - "\U000023F1 Extend 30 min:/rmt_computer_limit_extend, \U0001F6A8 Disable limit:/rmt_computer_limit_disable"
          - "\U0000267B Dismiss:/dismiss"

- alias: "computer_inactive_warning"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: numeric_state
      entity_id: sensor.state_change_seat_ago_min
      above: 30
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U000026A0 Computer inactive {{ states.sensor.state_change_seat_ago_min.state_with_unit }}"
        inline_keyboard:
          - "\U0001F4A4 Sleep:/rmt_computer_sleep, \U0000267B Dismiss:/dismiss"

- alias: "computer_high_consumption_warning"
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition:
    - condition: numeric_state
      entity_id: sensor.power_strip_1_load_power
      above: 200
      for:
        minutes: 60
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U0001f50c Computer high consumption for 60 minutes! {{ states.sensor.power_strip_1_load_power.state_with_unit }}"
        inline_keyboard:
          - "\U0001F4A4 Sleep:/rmt_computer_sleep, \U0000267B Dismiss:/dismiss"

- alias: "computer_inactive_action"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: numeric_state
      entity_id: sensor.state_change_seat_ago_min
      above: 60
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U0001F4BA Computer inactive {{ states.sensor.state_change_seat_ago_min.state_with_unit }}, turning off"
    - service:  script.rmt_computer_sleep
