- alias: "cube_action_rotate_right"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00028776ae_action
      to: "rotate_right"
  action:
    - service: script.light_adjust_brightness
      data_template:
        entity_id: light.livingroom
        step: 50

- alias: "cube_action_rotate_left"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00028776ae_action
      to: "rotate_left"
  action:
    - service: script.light_adjust_brightness
      data_template:
        entity_id: light.livingroom
        step: -50

- alias: "cube_action_flip90"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00028776ae_action
      to: "flip90"
  action:
    - service: script.light_adjust_color_temp
      data_template:
        entity_id: light.livingroom_color
        step: 80

- alias: "cube_action_flip180"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00028776ae_action
      to: "flip180"
  action:
    - service: script.light_adjust_color_temp
      data_template:
        entity_id: light.livingroom_color
        step: -80

- alias: "cube_action_fall"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00028776ae_action
      to: "fall"
  action:
    - service: script.rmt_computer_sleep
    - service: script.turn_on
      entity_id: script.light_good_night
    - service: media_player.turn_off
      entity_id: all

- alias: "cube_action_shake"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00028776ae_action
      to: "shake"
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_on_min