- alias: "cube_action_rotate_when_flow_is_off"
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028776ae
      action_type: rotate
  condition:
  - condition: state
    entity_id: sensor.livingroom_ambient_flow_is_on
    state: "False"
  action:
  - service: light.turn_on
    entity_id: light.livingroom_ambient
    data_template:
      brightness: >
        {% set br = states.light.livingroom_ambient.attributes.brightness | int %}
        {% set br_min = 1 | int %}
        {% set br_max = 255 | int %}
        {% set step = 50 | int %}
        {% if trigger.event.data.action_value | default('0') | float < 0 %}
          {% if br > br_min + step %}
            {% set br = br - step %}
          {% else %}
            {% set br = br_min %}
          {% endif %}
        {% else %}
          {% if br < br_max - step %}
            {% set br = br + step %}
          {% else %}
            {% set br = br_max %}
          {% endif %}
        {% endif %}
        {{ br }}

- alias: "cube_action_rotate_when_flow_is_on"
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028776ae
      action_type: rotate
  condition:
  - condition: state
    entity_id: sensor.livingroom_ambient_flow_is_on
    state: "True"
  action:
  - service: input_number.set_value
    entity_id: input_number.flow_brightness
    data_template:
      value: >
        {% set br = states.input_number.flow_brightness.state | int %}
        {% set br_min = 1 | int %}
        {% set br_max = 255 | int %}
        {% set step = 50 | int %}
        {% if trigger.event.data.action_value | default('0') | float < 0 %}
          {% if br > br_min + step %}
            {% set br = br - step %}
          {% else %}
            {% set br = br_min %}
          {% endif %}
        {% else %}
          {% if br < br_max - step %}
            {% set br = br + step %}
          {% else %}
            {% set br = br_max %}
          {% endif %}
        {% endif %}
        {{ br }}

#- alias: "cube_action_v2"
#  initial_state: 'on'
#  trigger:
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: flip90
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: flip180
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: move
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: free_fall
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: shake_air
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: tap_twice
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: swing
#  - platform: event
#    event_type: cube_action
#    event_data:
#      entity_id: binary_sensor.cube_158d00028776ae
#      action_type: iam
##  - platform: event
##    event_type: cube_action
##    event_data:
##      entity_id: binary_sensor.cube_158d00028776ae
##      action_type: alert
##  - platform: event
##    event_type: cube_action
##    event_data:
##      entity_id: binary_sensor.cube_158d00028776ae
##      action_type: rotate
#  action:
#  - service: telegram_bot.send_message
#    data_template:
#      target: !secret tg_chat_dima
#      message: "\U0001F3B2 Cube is `{{ trigger.event.data.action_type }}  {{ trigger.event.data.action_value | default('0') }}`"