- alias: "cube_action_rotate"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: rotate
  action:
    - service: script.light_adjust_brightness
      data_template:
        entity_id: light.livingroom
        step: >
          {% if trigger.event.data.action_value | default('0') | float < 0 %}
            -50
          {% else %}
            50
          {% endif %}

- alias: "cube_action_flip90"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: flip90
  action:
    - service: script.light_adjust_color_temp
      data_template:
        entity_id: light.livingroom_color
        step: 80

- alias: "cube_action_flip180"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: flip180
  action:
    - service: script.light_adjust_color_temp
      data_template:
        entity_id: light.livingroom_color
        step: -80

- alias: "cube_action_free_fall"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: free_fall
  action:
    - service: script.rmt_computer_sleep
    - service: script.turn_on
      entity_id: script.light_good_night
    - service: media_player.turn_off
      entity_id: all

- alias: "cube_action_shake_air"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: shake_air
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_on_min

#   action_type: move
#   action_type: swing
#   action_type: iam
#   action_type: alert
