- alias: "cube_action_rotate"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: rotate
  action:
    - service: light.turn_on
      entity_id: light.livingroom
      data_template:
        brightness: >
          {% set current = states.light.livingroom.attributes.brightness | int %}
          {% set min = 1 | int %}
          {% set max = 255 | int %}
          {% set step = 50 | int %}
          {% if trigger.event.data.action_value | default('0') | float < 0 %}
            {% if current > min + step %}
              {% set current = current - step %}
            {% else %}
              {% set current = min %}
            {% endif %}
          {% else %}
            {% if current < max - step %}
              {% set current = current + step %}
            {% else %}
              {% set current = max %}
            {% endif %}
          {% endif %}
          {{ current }}

- alias: "cube_action_flip90"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: flip90
  action:
    - service: light.turn_on
      entity_id: light.livingroom
      data_template:
        color_temp: >
          {% set current = states.light.livingroom.attributes.color_temp | int %}
          {% set min = 153 | int %}
          {% set max = 588 | int %}
          {% set step = 80 | int %}
          {% if current < max - step %}
            {% set current = current + step %}
          {% else %}
            {% set current = max %}
          {% endif %}
          {{ current }}

- alias: "cube_action_flip180"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: flip180
  action:
    - service: light.turn_on
      entity_id: light.livingroom
      data_template:
        color_temp: >
          {% set current = states.light.livingroom.attributes.color_temp | int %}
          {% set min = 153 | int %}
          {% set max = 588 | int %}
          {% set step = 80 | int %}
          {% if current > min + step %}
            {% set current = current - step %}
          {% else %}
            {% set current = min %}
          {% endif %}
          {{ current }}

- alias: "cube_action_free_fall"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: free_fall
  action:
    - service: script.rmt_computer_sleep
    - service: script.turn_on
      entity_id: script.light_good_night
    - service: media_player.turn_off
      entity_id: all

- alias: "cube_action_shake_air"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: shake_air
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_on_min

#   action_type: move
#   action_type: swing
#   action_type: iam
#   action_type: alert
