- alias: "cube_action_rotate_when_flow_is_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: rotate
  condition:
    - condition: state
      entity_id: sensor.livingroom_ambient_flow_is_on
      state: "False"
  action:
    - service: light.turn_on
      entity_id: light.group_livroom_ambient
      data_template:
        brightness: >
          {% set current = states.light.group_livroom_ambient.attributes.brightness | int %}
          {% set min = 1 | int %}
          {% set max = 255 | int %}
          {% set step = 50 | int %}
          {% if trigger.event.data.action_value | default('0') | float < 0 %}
            {% if current > min + step %}
              {% set current = current - step %}
            {% else %}
              {% set current = min %}
            {% endif %}
          {% else %}
            {% if current < max - step %}
              {% set current = current + step %}
            {% else %}
              {% set current = max %}
            {% endif %}
          {% endif %}
          {{ current }}

- alias: "cube_action_flip90_when_flow_is_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: flip90
  condition:
    - condition: state
      entity_id: sensor.livingroom_ambient_flow_is_on
      state: "False"
  action:
    - service: light.turn_on
      entity_id: light.group_livroom_ambient
      data_template:
        color_temp: >
          {% set current = states.light.group_livroom_ambient.attributes.color_temp | int %}
          {% set min = 153 | int %}
          {% set max = 588 | int %}
          {% set step = 80 | int %}
          {% if current < max - step %}
            {% set current = current + step %}
          {% else %}
            {% set current = max %}
          {% endif %}
          {{ current }}

- alias: "cube_action_flip180_when_flow_is_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: flip180
  condition:
    - condition: state
      entity_id: sensor.livingroom_ambient_flow_is_on
      state: "False"
  action:
    - service: light.turn_on
      entity_id: light.group_livroom_ambient
      data_template:
        color_temp: >
          {% set current = states.light.group_livroom_ambient.attributes.color_temp | int %}
          {% set min = 153 | int %}
          {% set max = 588 | int %}
          {% set step = 80 | int %}
          {% if current > min + step %}
            {% set current = current - step %}
          {% else %}
            {% set current = min %}
          {% endif %}
          {{ current }}

- alias: "cube_action_rotate_when_flow_is_on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: rotate
  condition:
    - condition: state
      entity_id: sensor.livingroom_ambient_flow_is_on
      state: "True"
  action:
    - service: input_number.set_value
      entity_id: input_number.flow_brightness
      data_template:
        value: >
          {% set current = states.input_number.flow_brightness.state | int %}
          {% set min = 1 | int %}
          {% set max = 255 | int %}
          {% set step = 50 | int %}
          {% if trigger.event.data.action_value | default('0') | float < 0 %}
            {% if current > min + step %}
              {% set current = current - step %}
            {% else %}
              {% set current = min %}
            {% endif %}
          {% else %}
            {% if current < max - step %}
              {% set current = current + step %}
            {% else %}
              {% set current = max %}
            {% endif %}
          {% endif %}
          {{ current }}

- alias: "cube_action_free_fall"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: free_fall
  action:
    - service: script.rmt_computer_sleep
    - service: scene.turn_on
      entity_id: scene.good_night

- alias: "cube_action_shake_air"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00028776ae
        action_type: shake_air
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_light_on_low

#   action_type: move
#   action_type: tap_twice
#   action_type: swing
#   action_type: iam
#   action_type: alert
