- alias: "computer_power_strip_off"
  trigger:
    - platform: time
      at: "02:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.power_strip_1

- alias: "computer_power_strip_on"
  trigger:
    - platform: time
      at: "06:50:00"
  action:
    - service: switch.turn_on
      entity_id: switch.power_strip_1

- alias: "computer_turned_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_computer
      from: "on"
      to: "off"
      for:
        minutes: 1
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U0001F5A5 is turned off ({{ states.sensor.computer_on_today.state_with_unit }})"

- alias: "computer_turned_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_computer
      from: "off"
      to: "on"
      for:
        minutes: 2
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U0001F5A5 is turned on ({{ states.sensor.computer_on_today.state_with_unit }})"

- alias: "laptop_turned_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_laptop
      from: "on"
      to: "off"
      for:
        minutes: 1
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U0001F4BB is turned off ({{ states.sensor.laptop_on_today.state_with_unit }})"

- alias: "laptop_turned_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_laptop
      from: "off"
      to: "on"
      for:
        minutes: 2
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U0001F4BB is turned on ({{ states.sensor.laptop_on_today.state_with_unit }})"