- alias: "entrance_button_single_if_people_home_on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00021329e3
        click_type: single
  condition:
    - condition: state
      entity_id: binary_sensor.people_home
      state: "on"
  action:
    - delay: "00:00:15"
    - service: scene.turn_on
      entity_id: scene.we_are_leaving
    - service: script.media_radio_stop_all
    - service: script.rmt_computer_sleep
    - service: script.rmt_laptop_sleep

- alias: "entrance_button_single_if_people_home_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00021329e3
        click_type: single
  condition:
    - condition: state
      entity_id: binary_sensor.people_home
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.we_are_arriving
    - service: script.media_radio_play_soma_lounge