#- alias: "standalone_left_single"
#  trigger:
#    - platform: event
#      event_type: xiaomi_aqara.click
#      event_data:
#        entity_id: binary_sensor.wall_switch_left_158d00026b96c1
#        click_type: single
#  action:
#    - service: light.toggle
#      entity_id: light.tree_lamp

- alias: "standalone_left_right_when_small_torch_on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00026b96c1
        click_type: single
  condition:
    condition: state
    entity_id: light.small_torch
    state: "on"
  action:
    - service: light.turn_off
      entity_id: light.small_torch

- alias: "standalone_left_right_when_small_torch_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00026b96c1
        click_type: single
  condition:
    condition: state
    entity_id: light.small_torch
    state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.small_torch_on_full

- alias: "light_button_single_when_light_is_on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002136276
        click_type: single
  condition:
    - condition: state
      entity_id: light.group_livroom_ambient
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_light_off

- alias: "light_button_single_when_light_is_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002136276
        click_type: single
  condition:
    - condition: state
      entity_id: light.group_livroom_ambient
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_light_on_from_btn

- alias: "light_button_double_when_flow_is_off"
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002136276
      click_type: double
  condition:
  - condition: state
    entity_id: sensor.livingroom_ambient_flow_is_on
    state: "False"
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_flow_on

- alias: "light_button_double_when_flow_is_on"
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002136276
      click_type: double
  condition:
  - condition: state
    entity_id: sensor.livingroom_ambient_flow_is_on
    state: "True"
  action:
  - service: script.light_flow_next

- alias: "light_livingroom_flow"
  trigger:
  - platform: time
    seconds: "/5"
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.livingroom_torch_use
      state: "on"
    - condition: state
      entity_id: input_boolean.livingroom_corner_use
      state: "on"
  action:
  - service: script.flow_idx_update
  - service: script.light_turn_on_hs
    data_template:
      id: >
        {% if is_state('input_boolean.livingroom_torch_use', 'on') and is_state('input_boolean.livingroom_corner_use', 'on') %}
          light.big_torch,light.corner_lamp
        {% elif is_state('input_boolean.livingroom_torch_use', 'on') %}
          light.big_torch
        {% elif is_state('input_boolean.livingroom_corner_use', 'on') %}
          light.corner_lamp
        {% endif %}
      hue: >
        {% if is_state('input_select.living_room_flow', 'custom') %}
          {% set hue = {
            1 : states.input_number.flow_custom_hue1.state | int,
            2 : states.input_number.flow_custom_hue2.state | int,
            3 : states.input_number.flow_custom_hue3.state | int,
            4 : states.input_number.flow_custom_hue4.state | int
          } %}
        {% elif is_state('input_select.living_room_flow', 'random') %}
          {% set hue = {
            1 : states.sensor.flow_random_hue.state | int,
            2 : states.sensor.flow_random_hue.state | int,
            3 : states.sensor.flow_random_hue.state | int,
            4 : states.sensor.flow_random_hue.state | int
          } %}
        {% else %}
          {% set hue = {
            1 : states.input_number.flow_hue1.state | int,
            2 : states.input_number.flow_hue2.state | int,
            3 : states.input_number.flow_hue3.state | int,
            4 : states.input_number.flow_hue4.state | int
          } %}
        {% endif %}
        {{hue[states.input_number.flow_idx.state|int]}}
      sat: "{{ states.input_number.flow_saturation.state }}"
      brightness: "{{ states.input_number.flow_brightness.state }}"
      transition: "{{ states.input_number.flow_transition.state }}"

- alias: "light_livingroom_flow_hues"
  trigger:
  - platform: state
    entity_id: input_select.living_room_flow
  action:
  - service: input_number.set_value
    entity_id: input_number.flow_hue1
    data_template:
      value: >
        {% set hue = {
          'purple' : 260,
          'red' : 340,
          'yellow' : 40,
          'green' : 100,
          'blue' : 200
        } %}
        {{hue[states.input_select.living_room_flow.state]}}
  - service: input_number.set_value
    entity_id: input_number.flow_hue2
    data_template:
      value: >
        {% set hue = {
          'purple' : 280,
          'red' : 360,
          'yellow' : 60,
          'green' : 120,
          'blue' : 220
        } %}
        {{hue[states.input_select.living_room_flow.state]}}
  - service: input_number.set_value
    entity_id: input_number.flow_hue3
    data_template:
      value: >
        {% set hue = {
          'purple' : 300,
          'red' : 20,
          'yellow' : 80,
          'green' : 140,
          'blue' : 240
        } %}
        {{hue[states.input_select.living_room_flow.state]}}
  - service: input_number.set_value
    entity_id: input_number.flow_hue4
    data_template:
      value: >
        {% set hue = {
          'purple' : 320,
          'red' : 40,
          'yellow' : 100,
          'green' : 160,
          'blue' : 260
        } %}
        {{hue[states.input_select.living_room_flow.state]}}