- alias: "outside_temperature_calc_diff"
  initial_state: "on"
  trigger:
    platform: state
    entity_id:
    - sensor.outside_temperature_min
    - sensor.outside_temperature_max
  action:
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/diff"
      payload: "{{ (states.sensor.outside_temperature_max.state | float - states.sensor.outside_temperature_min.state | float) | round(1)}}"
      retain: true

#- alias: "cube_action"
#  initial_state: "on"
#  trigger:
#    platform: state
#    entity_id:
#    - binary_sensor.cube_158d00028776ae
#  action:
#  - service: mqtt.publish
#    data_template:
#      topic: "{{ trigger.from_state.attributes.friendly_name }}"
#      payload: "{{ trigger.to_state.state }}"
#      retain: true