- alias: "outside_temperature_calc_diff"
  initial_state: "on"
  trigger:
  - platform: state
    entity_id:
    - sensor.outside_temperature_min
    - sensor.outside_temperature_max
  action:
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/diff"
      payload: "{{ (states.sensor.outside_temperature_max.state | float - states.sensor.outside_temperature_min.state | float) | round(1)}}"
      retain: true

- alias: "alert_coffee_machine_works_too_long"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_strip_5_load_power
      above: 12500
      for:
        minutes: 12
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
          - !secret tg_chat_dima
          - !secret tg_chat_alyona
        message: "{{ now().strftime('%H:%M') }} \U00002615 Turn off coffee machine!"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"