- alias: "outside_temperature_calc_diff"
  trigger:
  - platform: state
    entity_id:
    - sensor.outside_temperature_min
    - sensor.outside_temperature_max
  action:
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/diff"
      payload: "{{ (states.sensor.outside_temperature_max.state | float - states.sensor.outside_temperature_min.state | float) | round(1)}}"
      retain: true

- alias: "computer_limiter"
  trigger:
    - platform: time
      seconds: "/300"
  condition:
    - condition: state
      entity_id: input_boolean.computer_today_limit
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
    - condition: template
      value_template: "{{ states.sensor.computer_on_today_minutes.state | int >= states.input_number.computer_today_allowed.state | int}}"
  action:
    - service: notify.telegram_dima
      data_template:
        message: "{{ now().strftime('%H:%M') }} \U0001F914 Computer limit passed. Turning off"
    - service:  script.rmt_computer_sleep