- alias: "mobile_nfc_purple_tag_dima"
  trigger:
    - platform: event
      event_type: tag_scanned
      event_data:
        device_id: !secret device_id_dima
        tag_id: 3d44c76d-1995-4eba-97e3-1f8576ac38f0
  action:
    - service: script.tts_outside

- alias: "mobile_share_youtube_link"
  trigger:
    - platform: event
      event_type: mobile_app.share
  action:
    - choose:
      - conditions: "{{ 'youtu' in trigger.event.data.url }}"
        sequence:
          - service: script.cast_youtube_url
            data:
              url: "{{ trigger.event.data.url }}"
      default:
          - service: notify.telegram_dima
            data:
              message: "{{ states('sensor.now_hm') }} MobAppShare `{{ trigger.event }}`"

- alias: "yury_phone_is_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.redmi_note_9_pro_interactive
      from: "off"
      to: "on"
      for:
        seconds: 60
  condition: "{{ is_state('binary_sensor.is_yury_phone_overdue', 'on') }}"
  action:
    - service: notify.telegram_parents
      data:
        message: "{{ states('sensor.now_hm') }} ☎️ Yury's is on. Today: {{ states['sensor.yury_interactive'].state_with_unit }}"

- alias: "yury_phone_is_on_and_overdue"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition: 
    - "{{ is_state('binary_sensor.redmi_note_9_pro_interactive', 'on') }}"
    - "{{ is_state('binary_sensor.is_yury_phone_overdue', 'on') }}"
  action:
    - service: notify.telegram_dima
      data:
        message: "{{ states('sensor.now_hm') }} 📵 Yury's STILL on. Today: {{ states['sensor.yury_interactive'].state_with_unit }}"
