- alias: "update_input_text_radio_cast"
  trigger:
    - platform: state
      entity_id: input_select.radio_cast
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.radio_cast
        value: >
          {% if is_state("input_select.radio_cast", "Kitchen speaker") %} media_player.kitchen_display
          {% elif is_state("input_select.radio_cast", "Loud speaker") %} media_player.loud_speaker
          {% elif is_state("input_select.radio_cast", "Yuri speaker") %} media_player.yury_speaker
          {% elif is_state("input_select.radio_cast", "Chromecast") %} media_player.chromecast0541
          {% elif is_state("input_select.radio_cast", "All") %} media_player.speakers
          {% endif %}