- alias: "update_input_text_radio_cast"
  trigger:
    - platform: state
      entity_id: input_select.radio_cast
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.radio_cast
        value: >
          {% if is_state("input_select.radio_cast", "Kitchen speaker") %} media_player.kitchen_display
          {% elif is_state("input_select.radio_cast", "Loud speaker") %} media_player.loud_speaker
          {% elif is_state("input_select.radio_cast", "Yury speaker") %} media_player.yury_speaker
          {% elif is_state("input_select.radio_cast", "Black speaker") %} media_player.black_speaker
          {% elif is_state("input_select.radio_cast", "Speakers") %} media_player.speakers
          {% elif is_state("input_select.radio_cast", "Surround") %} media_player.surround
          {% endif %}