- alias: "autoupdate_radio_cast_device_text"
  trigger:
    - platform: state
      entity_id: input_select.radio_cast_device
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.radio_cast_device
        value: >
          {% if is_state("input_select.radio_cast_device", "Kitchen speaker") %} media_player.kitchen_display
          {% elif is_state("input_select.radio_cast_device", "Loud speaker") %} media_player.loud_speaker
          {% elif is_state("input_select.radio_cast_device", "Tele2 speaker") %} media_player.tele2_speaker
          {% elif is_state("input_select.radio_cast_device", "Bathroom speaker") %} media_player.bathroom_speaker
          {% elif is_state("input_select.radio_cast_device", "Black speaker") %} media_player.black_speaker
          {% elif is_state("input_select.radio_cast_device", "Speakers") %} media_player.speakers
          {% elif is_state("input_select.radio_cast_device", "Surround") %} media_player.surround
          {% endif %}

- alias: "autoupdate_radio_station_name"
  trigger:
    - platform: state
      entity_id: input_select.radio_cast_station
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.radio_cast_station_name
        value: "{{ trigger.to_state.state }}"

- alias: "autoupdate_radio_station_url"
  trigger:
    - platform: state
      entity_id: input_text.radio_cast_station_name
  action:
    - service: input_text.set_value
      data:
        entity_id: input_text.radio_cast_station_url
        value: >
          {% if is_state("input_text.radio_cast_station_name", "Frequence3") %} http://ice.stream.frequence3.net/frequence3-128.mp3
          {% elif is_state("input_text.radio_cast_station_name", "MoskvaFM") %} http://icecast.vgtrk.cdnvideo.ru/moscowfm128
          {% elif is_state("input_text.radio_cast_station_name", "Groove salad") %} http://ice1.somafm.com/groovesalad-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Illinois lounge") %} http://ice1.somafm.com/illstreet-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Thistle radio") %} http://ice1.somafm.com/thistle-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Secret agent") %} http://ice1.somafm.com/secretagent-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Deep space one") %} http://ice1.somafm.com/deepspaceone-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Covers") %} http://ice1.somafm.com/covers-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Seventies") %} http://ice1.somafm.com/seventies-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Beat blender") %} http://ice1.somafm.com/beatblender-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Vaporwaves") %} http://ice1.somafm.com/vaporwaves-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Space station") %} http://ice1.somafm.com/spacestation-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Drone zone") %} http://ice1.somafm.com/dronezone-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "The trip") %} http://ice1.somafm.com/thetrip-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Fluid") %} http://ice1.somafm.com/fluid-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Sonic universe") %} http://ice1.somafm.com/sonicuniverse-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Pop tron") %} http://ice1.somafm.com/poptron-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Lush") %} http://ice1.somafm.com/lush-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "Boot liquor") %} http://ice1.somafm.com/bootliquor-128-mp3
          {% elif is_state("input_text.radio_cast_station_name", "7 inch soul") %} http://ice1.somafm.com/7soul-128-mp3
          {% endif %}