- alias: "ha_startup"
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: script.ha_set_defaults
  - service: automation.trigger
    data_template:
      entity_id:
        - automation.update_input_text_radio_cast