- alias: "sun_sunrise"
  trigger:
    - platform: state
      entity_id: sun.sun
      to: "above_horizon"
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.sunrise
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} 🌅 {{ states['sensor.solar_elevation'].state_with_unit}}, {{ states['sensor.solar_azimuth'].state_with_unit}} #sun #sunrise"

- alias: "sun_sunset"
  trigger:
    - platform: state
      entity_id: sun.sun
      to: "below_horizon"
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.sunset
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} 🌇 {{ states['sensor.solar_elevation'].state_with_unit}}, {{ states['sensor.solar_azimuth'].state_with_unit}} #sun #sunset"

- alias: "sun_zenith"
  trigger:
    - platform: state
      entity_id: binary_sensor.sun_is_rising
      from: "on"
      to: "off"
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.zenith
    - service: input_number.set_value
      data:
        value: "{{ states('sensor.solar_elevation') }}"
        entity_id: input_number.zenith
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} 🌞 {{ states['sensor.solar_elevation'].state_with_unit}}, {{ states['sensor.solar_azimuth'].state_with_unit}} #sun #zenith"

- alias: "sun_nadir"
  trigger:
    - platform: state
      entity_id: binary_sensor.sun_is_rising
      from: "off"
      to: "on"
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.nadir
    - service: input_number.set_value
      data:
        value: "{{ states('sensor.solar_elevation') }}"
        entity_id: input_number.nadir
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} 🌃 {{ states['sensor.solar_elevation'].state_with_unit}}, {{ states['sensor.solar_azimuth'].state_with_unit}} #sun #nadir"