- alias: "ha_startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.androidbox_refresh_temp

- alias: "ha_rpi_power_tracker"
  trigger:
    - platform: state
      entity_id: binary_sensor.rpi_power_status
      to: "off"
      for:
        minutes: 10
  action:
    - service: notify.telegram_dima
      data:
        message: "{{ states('sensor.now_hm') }} 🔋 RPI Power issues"

- alias: "ha_hacs_updates"
  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: notify.telegram_dima
      data:
        message: "{{ states('sensor.now_hm') }} ⚜️ HASC updated available: {{ states('sensor.hacs') }}"

- alias: "ha_do_backup"
  condition:
    - condition: state
      entity_id: binary_sensor.is_backup_day
      state: "on"
  trigger:
    - platform: time
      at: "02:00:00"
  action:
    - service: script.ha_do_backup