- alias: "ha_startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: automation.trigger
      data:
        entity_id: automation.update_input_text_radio_cast
    - service: homeassistant.update_entity
      data:
        entity_id:
          - binary_sensor.is_holiday
          - binary_sensor.is_workday
          - binary_sensor.is_morning_activity
          - binary_sensor.is_backup_day
    - service: hassio.addon_restart
      data:
        addon: 7ad98f9c_zigbee2mqtt

- alias: "ha_rpi_power_tracker"
  trigger:
    - platform: numeric_state
      entity_id: sensor.rpi_power_status
      value_template: '{{ state.attributes.value }}'
      above: 0
      for:
        minutes: 10
  action:
    - service: persistent_notification.create
      data_template:
        title: "Power Supply Issue"
        message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }}"
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U0001f56f RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }}"

- alias: "ha_hacs_updates"
  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U0000269c HASC updated available: {{states.sensor.hacs.state}}"

- alias: "ha_midnight_daily_refresh"
  trigger:
    - platform: time
      at: "00:00:01"
  action:
    - service: counter.reset
      entity_id: counter.yuryroom_motions_watch

- alias: "ha_do_backup"
  condition:
    - condition: state
      entity_id: binary_sensor.is_backup_day
      state: "on"
  trigger:
    - platform: time
      at: "02:00:00"
  action:
    - service: script.ha_do_backup