- alias: "ha_startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.ha_set_defaults
    - service: automation.trigger
      data_template:
        entity_id:
          - automation.update_input_text_radio_cast
    - service: script.input_text_set_now
      data_template:
        entity_id: input_text.state_change_seat
    - service: homeassistant.update_entity
      data_template:
        entity_id:
          - binary_sensor.is_holiday
          - binary_sensor.is_workday
          - binary_sensor.is_morning_activity
          - binary_sensor.is_backup_day

- alias: "rpi_power_tracker"
  trigger:
    - platform: numeric_state
      entity_id: sensor.rpi_power_status
      value_template: '{{ state.attributes.value }}'
      above: 0
      for:
        minutes: 10
  action:
    - service: persistent_notification.create
      data_template:
        title: "Power Supply Issue"
        message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }}"
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001f56f RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }}"

- alias: "hacs_updates"
  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0000269c HASC updated available: {{states.sensor.hacs.state}}"
