- alias: "ha_startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: automation.trigger
      entity_id: automation.update_input_text_radio_cast
    - service: script.androidbox_refresh_temp

- alias: "ha_rpi_power_tracker"
  trigger:
    - platform: state
      entity_id: binary_sensor.rpi_power_status
      to: "off"
      for:
        minutes: 10
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001f56f RPI Power issues"

- alias: "ha_hacs_updates"
  trigger:
    - platform: numeric_state
      entity_id: sensor.hacs
      above: 0
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0000269c HASC updated available: {{ states('sensor.hacs') }}"

- alias: "ha_midnight_daily_refresh"
  trigger:
    - platform: time
      at: "00:00:01"
  action:
    - service: counter.reset
      entity_id: counter.yuryroom_motions_watch

- alias: "ha_do_backup"
  condition:
    - condition: state
      entity_id: binary_sensor.is_backup_day
      state: "on"
  trigger:
    - platform: time
      at: "02:00:00"
  action:
    - service: script.ha_do_backup