- alias: "t2speaker_volume_btn1_single"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_1_single"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "{{ state_attr('media_player.tele2_speaker', 'volume_level') | float + 0.01 }}"

- alias: "t2speaker_volume_btn2_single"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_2_single"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "{{ state_attr('media_player.tele2_speaker', 'volume_level') | float - 0.01 }}"

- alias: "t2speaker_volume_btn1_double"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_1_double"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "{{ state_attr('media_player.tele2_speaker', 'volume_level') | float + 0.05 }}"

- alias: "t2speaker_volume_btn2_double"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_2_double"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "{{ state_attr('media_player.tele2_speaker', 'volume_level') | float - 0.05 }}"

- alias: "t2speaker_volume_btn1_triple"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_1_triple"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "{{ state_attr('media_player.tele2_speaker', 'volume_level') | float + 0.1 }}"

- alias: "t2speaker_volume_btn2_triple"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_2_triple"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "{{ state_attr('media_player.tele2_speaker', 'volume_level') | float - 0.1 }}"

- alias: "t2speaker_volume_btn1_hold"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_1_hold"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "0.07"

- alias: "t2speaker_volume_btn2_hold"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_2_hold"
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.tele2_speaker
        volume_level: "0.0"
    # - service: media_player.volume_mute
    #   data:
    #     entity_id: media_player.tele2_speaker
    #     is_volume_muted: "{{ state_attr('media_player.tele2_speaker', 'is_volume_muted') != true }}"

#=== B3
- alias: "t2speaker_volume_btn3_single"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_3_single"
  action:
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "http://ice1.somafm.com/groovesalad-128-mp3" #soma groove

- alias: "t2speaker_volume_btn3_double"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_3_double"
  action:
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "http://ice1.somafm.com/deepspaceone-128-mp3" #soma deep space

#=== B4
- alias: "t2speaker_volume_btn4_single"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_4_single"
  action:
    - service: script.mobile_notify_dima
      data:
        message: "F3"
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "http://ice.stream.frequence3.net/frequence3-128.mp3" #f3

- alias: "t2speaker_volume_btn4_double"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_4_double"
  action:
    - service: script.mobile_notify_dima
      data:
        message: "Europa+"
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "http://ep256.streamr.ru/" #europa+

#=== B5
- alias: "t2speaker_volume_btn5_single"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_5_single"
  action:
    - service: script.mobile_notify_dima
      data:
        message: "Echo"
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "https://icecast-echomsksni.cdnvideo.ru/stream2" #echo

- alias: "t2speaker_volume_btn5_double"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_5_double"
  action:
    - service: script.mobile_notify_dima
      data:
        message: "Kommersant"
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "https://kommersant77.hostingradio.ru:8085/kommersant128.mp3" #kommersant

#=== B6
- alias: "t2speaker_volume_btn6_single"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_6_single"
  action:
    - service: script.mobile_notify_dima
      data:
        message: "MixFm"
    - service: script.media_radio_play_by_param
      data:
        entity_id: media_player.tele2_speaker
        media_content_id: "https://radio.mixnews.lv/MixFM" #mix

- alias: "t2speaker_volume_btn6_hold"
  trigger:
    - platform: state
      entity_id: sensor.0x04cf8cdf3c7d9bef_action
      to: "button_6_hold"
  action:
    - service: script.mobile_notify_dima
      data:
        message: "Turning off"
    - service: media_player.turn_off
      entity_id: media_player.tele2_speaker