#- alias: "abox_app_changed"
#  trigger:
#    - platform: state
#      entity_id:
#        - sensor.abox_app
#  action:
#    - service: telegram_bot.send_message
#      data_template:
#        target: !secret tg_chat_dima
#        message: "{{ states.sensor.now_hm.state }} #ABOX {{ trigger.from_state.state }} -> {{ trigger.to_state.state }}"

- alias: "tv_turned_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_tv
      from: "on"
      to: "off"
  action:
    - service: script.abox_key_home_if_active
    - service: script.media_player_stop_chromecast_if_active