- alias: "tv_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_tv
      to: "off"
      for:
        minutes: 1
  action:
    - service: script.androidbox_key_home
    - service: script.hyperion_off


- alias: "tv_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_tv
      to: "on"
  action:
    - service: script.hyperion_on_v4l

- alias: "hyperion_rpi_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_rpi3
      to: "on"
  action:
    - service: script.hyperion_off