- alias: "outpark_temp_calc_diff"
  trigger:
    - platform: state
      entity_id:
        - sensor.outpark_temp_min
        - sensor.outpark_temp_max
  action:
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/diff"
        payload: "{{ (states.sensor.outpark_temp_max.state | float - states.sensor.outpark_temp_min.state | float) | round(1) }}"
        retain: true

- alias: "outyard_temp_calc_diff"
  trigger:
    - platform: state
      entity_id:
        - sensor.outyard_temp_min
        - sensor.outyard_temp_max
  action:
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/diff"
        payload: "{{ (states.sensor.outyard_temp_max.state | float - states.sensor.outyard_temp_min.state | float) | round(1) }}"
        retain: true