- alias: "outpark_temperature_calc_diff"
  trigger:
    - platform: state
      entity_id:
        - sensor.outpark_temperature_min
        - sensor.outpark_temperature_max
  action:
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/diff"
        payload: "{{ (states.sensor.outpark_temperature_max.state | float - states.sensor.outpark_temperature_min.state | float) | round(1) }}"
        retain: true

- alias: "outyard_temperature_calc_diff"
  trigger:
    - platform: state
      entity_id:
        - sensor.outyard_temperature_min
        - sensor.outyard_temperature_max
  action:
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/diff"
        payload: "{{ (states.sensor.outyard_temperature_max.state | float - states.sensor.outyard_temperature_min.state | float) | round(1) }}"
        retain: true