- alias: "zigbee_enable_join"
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: "on"
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: "true"
    - service: timer.start
      entity_id: timer.zigbee_permit_join

- alias: "zigbee_disable_join"
  trigger:
    - entity_id: input_boolean.zigbee_permit_join
      platform: state
      to: "off"
  action:
    - service: mqtt.publish
      data:
        payload: "false"
        topic: zigbee2mqtt/bridge/config/permit_join
    - service: timer.cancel
      entity_id: timer.zigbee_permit_join

- alias: "zigbee_disable_join_timer"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: "false"
    - service: input_boolean.turn_off
      entity_id: input_boolean.zigbee_permit_join