################## DIMA
- alias: "zone_dima_enters_work"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.work
      event: enter
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F4BC' }} Dima enters
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.dima'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_leaves_work"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.work
      event: leave
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F4BC' }} Dima leaves
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.dima'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_enters_home"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.home
      event: enter
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }} 
          {{ '\U0001F3E0' }} Dima enters 
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.dima'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_leaves_home"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.home
      event: leave
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F3E0' }} Dima leaves
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.dima'].state)) / 60) | int) }} minutes)
    - service: telegram_bot.send_location
      data:
        target: !secret tg_chat_dima
        latitude: "{{ states['person.dima'].attributes.latitude }}"
        longitude: "{{ states['person.dima'].attributes.longitude }}"
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_enters_school"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.school
      event: enter
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F3EB' }} Dima enters
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.dima'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_leaves_school"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.school
      event: leave
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F3EB' }} Dima leaves
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.dima'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_dima

################## ALYONA
- alias: "zone_alyona_enters_school"
  trigger:
    - platform: zone
      entity_id: person.alyona
      zone: zone.school
      event: enter
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F3EB' }} Alyona enters
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.alyona'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_alyona

- alias: "zone_alyona_leaves_school"
  trigger:
    - platform: zone
      entity_id: person.alyona
      zone: zone.school
      event: leave
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: >
          {{ states('sensor.now_hm') }}
          {{ '\U0001F3EB' }} Alyona leaves
          ({{ (((as_timestamp(now()) - as_timestamp(states['input_datetime.alyona'].state)) / 60) | int) }} minutes)
    - service: script.input_datetime_set_now_alyona