################## DIMA
- alias: "zone_dima_enters_work"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.work
      event: enter
  action:
    - service: script.refresh_durations
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F4BC Dima enters ({{ states['sensor.dima_duration_min'].state_with_unit }})"
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_leaves_work"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.work
      event: leave
  action:
    - service: script.refresh_durations
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F4BC Dima leaves ({{ states['sensor.dima_duration_min'].state_with_unit }})"
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_enters_home"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.home
      event: enter
  action:
    - service: script.refresh_durations
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F3E0 Dima enters ({{ states['sensor.dima_duration_min'].state_with_unit }})"
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_leaves_home"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.home
      event: leave
  action:
    - service: script.refresh_durations
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F3E0 Dima leaves ({{ states['sensor.dima_duration_min'].state_with_unit }})"
    - service: telegram_bot.send_location
      data:
        target: !secret tg_chat_dima
        latitude: "{{ states['person.dima'].attributes.latitude }}"
        longitude: "{{ states['person.dima'].attributes.longitude }}"
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_enters_school"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.school
      event: enter
  action:
    - service: script.refresh_durations
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F3EB Dima enters ({{ states['sensor.dima_duration_min'].state_with_unit }})"
    - service: script.input_datetime_set_now_dima

- alias: "zone_dima_leaves_school"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.school
      event: leave
  action:
    - service: script.refresh_durations
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F3EB Dima leaves ({{ states['sensor.dima_duration_min'].state_with_unit }})"
    - service: script.input_datetime_set_now_dima