################## DIMA
- alias: "zone_dima_enters_work"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.work
      event: enter
  action:
    - service: script.state_change_update_dima_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F4BC Dima enters ({{ states.sensor.state_change_dima_ago.state }})"
    - service: script.state_change_update_dima

- alias: "zone_dima_leaves_work"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.work
      event: leave
  action:
    - service: script.state_change_update_dima_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F4BC Dima leaves ({{ states.sensor.state_change_dima_ago.state }})"
    - service: script.state_change_update_dima

- alias: "zone_dima_enters_home"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.home
      event: enter
  action:
    - service: script.state_change_update_dima_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F3E0 Dima enters ({{ states.sensor.state_change_dima_ago.state }})"
    - service: script.state_change_update_dima

- alias: "zone_dima_leaves_home"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.home
      event: leave
  action:
    - service: script.state_change_update_dima_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F3E0 Dima leaves ({{ states.sensor.state_change_dima_ago.state }})"
    - service: script.state_change_update_dima

- alias: "zone_dima_enters_school"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.school
      event: enter
  action:
    - service: script.state_change_update_dima_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F3EB Dima enters ({{ states.sensor.state_change_dima_ago.state }})"
    - service: script.state_change_update_dima

- alias: "zone_dima_leaves_school"
  trigger:
    - platform: zone
      entity_id: person.dima
      zone: zone.school
      event: leave
  action:
    - service: script.state_change_update_dima_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F3EB Dima leaves ({{ states.sensor.state_change_dima_ago.state }})"
    - service: script.state_change_update_dima

################## ALYONA
- alias: "zone_alyona_enters_school"
  trigger:
    - platform: zone
      entity_id: person.alyona
      zone: zone.school
      event: enter
  action:
    - service: script.state_change_update_alyona_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F3EB Alyona enters ({{ states.sensor.state_change_alyona_ago.state }})"
    - service: script.state_change_update_alyona

- alias: "zone_alyona_leaves_school"
  trigger:
    - platform: zone
      entity_id: person.alyona
      zone: zone.school
      event: leave
  action:
    - service: script.state_change_update_alyona_ago
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F3EB Alyona leaves ({{ states.sensor.state_change_alyona_ago.state }})"
    - service: script.state_change_update_alyona