- id: '1594881803543'
  alias: Sun is up
  description: ''
  trigger:
  - entity_id: sun.sun
    platform: state
    to: above_horizon
  condition: []
  action:
  - service: telegram_bot.send_message
  mode: parallel
  max: 10
- id: '1594881932814'
  alias: Sun is up
  description: ''
  trigger:
  - entity_id: sun.sun
    platform: state
    to: above_horizon
  condition: []
  action:
  - service: telegram_bot.send_message
  mode: parallel
  max: 10
