homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  whitelist_external_dirs:
  - /config
  - /tmp
  - /share

map:
sun:
#discovery:
hassio:
config:
frontend:
  themes: !include_dir_merge_named includes/themes
  javascript_version: latest

lovelace:
  mode: yaml

updater:
  include_used_components: true

recorder: !include includes/recorder.yaml
history:
logbook:
logger:
  default: warn

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  base_url: !secret http_base_url_no_port

tts:
- platform: google
  language: ru

system_log:
  max_entries: 20

influxdb:
  host: 192.168.1.10
  port: 8086
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password

media_player:
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
- platform: kodi
  host: 192.168.1.20

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    key: !secret gw_key

telegram_bot:
  platform: polling
  api_key: !secret tg_api_bot_key
  allowed_chat_ids:
  - !secret tg_chat_dima
  - !secret tg_chat_yury
  - !secret tg_chat_alyona

device_tracker:
- platform: google_maps
  username: !secret bot_gmail_user
  password: !secret bot_gmail_pass
  interval_seconds: 850

google_assistant: !include includes/googleassistant.yaml
zone: !include includes/zone.yaml
input_number: !include includes/input_number.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
light: !include includes/light.yaml
#camera: !include includes/camera.yaml
notify: !include includes/notify.yaml
binary_sensor: !include includes/binary_sensor.yaml
shell_command: !include includes/shell_command.yaml

scene: !include_dir_merge_list includes/scenes
sensor: !include_dir_merge_list includes/sensors
switch: !include_dir_merge_list includes/switches
automation: !include_dir_merge_list includes/automation

script: !include_dir_merge_named includes/scripts
#history_graph: !include_dir_merge_named includes/historygraph
