homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs:
  - /config
  - /tmp
  - /share

stream:

map:
sun:
config:
system_health:
person:
system_log:
  max_entries: 20

frontend:
  themes: !include_dir_merge_named includes/themes
  javascript_version: latest

lovelace:
  mode: yaml

updater:
  include_used_components: true

influxdb: !include includes/influxdb.yaml
recorder: !include includes/recorder.yaml
history:
logbook:
custom_updater: !include includes/custom_updater.yaml

logger:
  default: warning
  logs:
    homeassistant.components.media_player: error
    homeassistant.components.script: error
    homeassistant.components.influxdb.sensor: error
    homeassistant.components.sensor: error
    homeassistant.helpers.entity: error
    homeassistant.components.androidtv.media_player: error
    homeassistant.components.template.sensor: error

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret http_base_url_no_port

tts:
- platform: google_translate
  service_name: google_say
  language: ru

#googlehome:
#  devices:
#    - host: 192.168.1.32
#      track_alarms: true

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    key: !secret gw_key

telegram_bot:
  platform: polling
  api_key: !secret tg_api_bot_key
  allowed_chat_ids:
  - !secret tg_chat_dima
  - !secret tg_chat_yury
  - !secret tg_chat_alyona

#calendar integration
google:
  client_id: !secret google_cal_int_client_id
  client_secret: !secret google_cal_int_client_secret
  track_new_calendar: true

input_number: !include includes/input_number.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_text: !include includes/input_text.yaml
counter: !include includes/counter.yaml
utility_meter: !include includes/utility_meter.yaml
light: !include includes/light.yaml
yeelight: !include includes/yeelight.yaml
google_assistant: !include includes/google_assistant.yaml
zone: !include includes/zone.yaml
device_tracker: !include includes/device_tracker.yaml
media_player: !include includes/media_player.yaml
notify: !include includes/notify.yaml
shell_command: !include includes/shell_command.yaml
timer: !include includes/timer.yaml
rest_command: !include includes/rest_command.yaml

scene: !include_dir_merge_list includes/scenes
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/binary_sensors
switch: !include_dir_merge_list includes/switches
automation: !include_dir_merge_list includes/automation

script: !include_dir_merge_named includes/scripts
camera: !include includes/camera.yaml
hassio:

group:
  sounds:
    name: "sounds"
    entities:
      - media_player.black_speaker
      - media_player.kitchen_display
      - media_player.loud_speaker
      - media_player.yury_speaker
      - media_player.chromecast
      - media_player.speakers
      - media_player.surround