resources:
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /local/tracker-card.js?v=0.1.4
    type: js

title: Home
views:
##################   MAIN
  - title: Main
    id: main
    icon: mdi:floor-plan
    cards:
    - type: vertical-stack
      cards:
      - type: glance
        title: Living room
        show_header_toggle: false
        entities:
          - entity: binary_sensor.motion_sensor_158d0001fa3dc0
            name: Motion
          - entity: sensor.livingroom_motions
            name: Motions
          - entity: sensor.illumination_158d0001fa3dc0
            name: Illumination
      - type: glance
        title: Bathroom
        show_header_toggle: false
        entities:
          - entity: binary_sensor.motion_sensor_158d0001e52779
            name: Motion
          - entity: sensor.bathroom_motions
            name: Motions
          - entity: sensor.illumination_158d0001e52779
            name: Illumination
          - entity: switch.wall_switch_right_158d00022391ec
            name: Light
            tap_action: toggle
      - type: glance
        title: Small corridor
        show_header_toggle: false
        entities:
          - entity: switch.wall_switch_left_158d00022391ec
            name: Light
            tap_action: toggle
      - type: glance
        title: Entrance
        show_header_toggle: false
        entities:
          - entity: light.entrance_garland
            name: Garland
            tap_action: toggle
          - entity: binary_sensor.door_window_sensor_158d00024367c8
            name: Door
            icon: mdi:door
          - entity: binary_sensor.switch_158d00021350ee
            name: Doorbell
            icon: mdi:bell
    - type: vertical-stack
      cards:
      - type: glance
        title: Outside
        show_header_toggle: false
        entities:
        - entity: sensor.temperature_158d00022c7cf2
          name: Temperature
        - entity: sensor.humidity_158d00022c7cf2
          name: Humidity
        - entity: sensor.pressure_158d00022c7cf2
          name: Pressure
        - entity: sensor.current_uv_index
          name: Current UV
        - entity: sensor.current_ozone_level
          name: Ozone level
      - type: glance
        title: Temperature Today
        show_header_toggle: false
        entities:
        - entity: sensor.outside_temperature_min
          name: Minimal
          icon: mdi:minus-box
        - entity: sensor.outside_temperature_max
          name: Maximal
          icon: mdi:plus-box
        - entity: sensor.outside_temperature_diff
          name: Difference
          icon: mdi:poll-box
        - entity: sensor.outside_temperature_min_at
          name: Minimal @
          icon: mdi:clock
        - entity: sensor.outside_temperature_max_at
          name: Maximal @
          icon: mdi:clock
      - type: glance
        title: Living room
        show_header_toggle: false
        entities:
        - entity: sensor.temperature_158d000234816a
          name: Temperature
        - entity: sensor.humidity_158d000234816a
          name: Humidity
        - entity: sensor.pressure_158d000234816a
          name: Pressure
      - type: glance
        title: Child room
        show_header_toggle: false
        entities:
        - entity: sensor.temperature_158d0002271609
          name: Temperature
        - entity: sensor.humidity_158d0002271609
          name: Humidity
        - entity: sensor.pressure_158d0002271609
          name: Pressure
      - type: glance
        title: Bedroom
        show_header_toggle: false
        entities:
        - entity: sensor.temperature_158d0001f23cbe
          name: Temperature
        - entity: sensor.humidity_158d0001f23cbe
          name: Humidity
        - entity: sensor.pressure_158d0001f23cbe
          name: Pressure
    - type: media-control
      entity: media_player.spotify
    - type: media-control
      entity: media_player.kodi

##################   SECONDARY
  - title: Secondary
    id: sec
    icon: mdi:link
    cards:
    - type: entities
      title: Links
      show_header_toggle: false
      entities:
      - type: weblink
        name: Router
        url: http://192.168.1.1/
        icon: mdi:router-wireless
      - type: weblink
        name: Sonoff 1
        url: http://192.168.1.40/
        icon: mdi:switch
      - type: weblink
        name: Influx DB
        url: http://192.168.1.10:8888
        icon: mdi:database
      - type: weblink
        name: Kodi
        url: http://192.168.1.20:8080
        icon: mdi:kodi
      - type: divider

      - type: weblink
        name: Lovelace
        url: https://www.home-assistant.io/lovelace
        icon: mdi:home-assistant
      - type: weblink
        name: Lovelace custom cards
        url: https://github.com/ciotlosm/custom-lovelace
        icon: mdi:home-assistant
      - type: weblink
        name: Light component
        url: https://www.home-assistant.io/components/light/
        icon: mdi:home-assistant
      - type: divider

      - type: weblink
        name: Automation conditions
        url: https://www.home-assistant.io/docs/automation/condition/
        icon: mdi:script
      - type: weblink
        name: Automation trigger
        url: https://www.home-assistant.io/docs/automation/trigger/
        icon: mdi:script
      - type: divider

      - type: weblink
        name: MDI icons
        url: https://materialdesignicons.com
        icon: mdi:sticker
      - type: weblink
        name: Emoji list
        url: http://unicode.org/emoji/charts/full-emoji-list.html
        icon: mdi:sticker-emoji
      - type: weblink
        name: Github repo
        url: https://github.com/omhy/ha
        icon: mdi:github-circle

    - type: entities
      title: Last changed
      show_header_toggle: false
      entities:
      - entity: sensor.door_state
        name: Door
        icon: mdi:door
        secondary_info: last-changed
      - entity: sensor.doorbell_state
        name: Doorbell
        icon: mdi:bell
        secondary_info: last-changed
      - type: divider
      - entity: sensor.livingroom_motion
        name: Living room
        icon: mdi:walk
        secondary_info: last-changed
      - type: divider
      - entity: sensor.bathroom_motion
        name: Bathroom
        icon: mdi:walk
        secondary_info: last-changed
      - entity: sensor.bathroom_switch
        name: Bathroom
        icon: mdi:lightbulb-on-outline
        secondary_info: last-changed
      - type: divider
      - entity: sensor.corridor_switch
        name: Corridor
        icon: mdi:lightbulb-on-outline
        secondary_info: last-changed

##################   LIGHTS
  - title: Lights
    id: lights
    icon: mdi:ceiling-light
    cards:
      - type: picture
        image: /local/colourtemp.jpg
      - type: entities
        title: Light sources
        show_header_toggle: false
        entities:
        - entity: light.livingroom_torch
          name: Torch
        - entity: light.livingroom_corner
          name: Corner
      - type: entities
        title: Torch
        show_header_toggle: true
        entities:
        - entity: input_number.livingroom_torch_brightness_pct
          name: Brightness %
        - entity: input_number.livingroom_torch_kelvin
          name: Kelvin t
      - type: entities
        title: Corner
        show_header_toggle: true
        entities:
        - entity: input_number.livingroom_corner_brightness_pct
          name: Brightness %
        - entity: input_number.livingroom_corner_kelvin
          name: Kelvin t

##################   LIGHTS FLOW
  - title: Lights flow
    id: lights_flow
    icon: mdi:palette
    cards:
      - type: vertical-stack
        cards:
        - type: glance
          title: Flow
          show_header_toggle: false
          entities:
          - entity: input_boolean.livingroom_torch_use
            name: Use torch
            icon: mdi:light-switch
            tap_action: call-service
            service: input_boolean.toggle
          - entity: input_boolean.livingroom_corner_use
            name: Use corner
            icon: mdi:light-switch
            tap_action: call-service
            service: input_boolean.toggle
          - entity: input_select.living_room_flow
            name: Flow type
        - type: entities
          title: Common settings
          show_header_toggle: true
          entities:
          - input_number.flow_transition
          - input_number.flow_brightness
          - input_number.flow_saturation
        - type: picture
          image: /local/hue.png
#      - type: custom:monster-card
#        card:
#          type: entities
#          title: Light scripts
#        filter:
#          include:
#          - entity_id: "script.light*"
      - type: conditional
        conditions:
        - entity: input_select.living_room_flow
          state_not: "custom"
        - entity: input_select.living_room_flow
          state_not: "random"
        card:
          type: entities
          title: Current flow settings
          entities:
          - input_number.flow_hue1
          - input_number.flow_hue2
          - input_number.flow_hue3
          - input_number.flow_hue4
      - type: conditional
        conditions:
          - entity: input_select.living_room_flow
            state: "custom"
        card:
          type: entities
          title: Custom flow settings
          entities:
          - input_number.flow_custom_hue1
          - input_number.flow_custom_hue2
          - input_number.flow_custom_hue3
          - input_number.flow_custom_hue4
#      - type: conditional
#        conditions:
#        - entity: input_select.living_room_flow
#          state: "random"
#        card:
#          type: entities
#          title: Randomiztor
#          entities:
#          - sensor.flow_random_hue

##################   ELECTRO
  - title: Electricity
    id: electro
    icon: mdi:power-plug
    cards:
      - type: glance
        title: Computer
        entities:
          - entity: sensor.power_strip_1_load_power
            name: Current
          - entity: sensor.power_computer_day
            name: Today
          - entity: sensor.power_computer_week
            name: Week
          - entity: sensor.power_computer_month
            name: Month
      - type: glance
        title: TV
        show_header_toggle: true
        entities:
          - entity: sensor.power_strip_4_load_power
            name: Current
          - entity: sensor.power_tv_day
            name: Today
          - entity: sensor.power_tv_week
            name: Week
          - entity: sensor.power_tv_month
            name: Month
      - type: glance
        title: Router
        show_header_toggle: true
        entities:
          - entity: sensor.power_strip_3_load_power
            name: Current
          - entity: sensor.power_router_day
            name: Today
          - entity: sensor.power_router_week
            name: Week
          - entity: sensor.power_router_month
            name: Month
      - type: glance
        title: Kitchen
        show_header_toggle: true
        entities:
          - entity: sensor.power_strip_2_load_power
            name: Current
          - entity: sensor.power_kitchen_day
            name: Today
          - entity: sensor.power_kitchen_week
            name: Week
          - entity: sensor.power_kitchen_month
            name: Month
      - type: glance
        title: Power cords
        show_header_toggle: false
        entities:
          - entity: switch.power_strip_1
            name: Computer
          - entity: switch.power_strip_3
            name: Router
          - entity: switch.power_strip_4
            name: TV
          - entity: switch.power_strip_2
            name: Kitchen

##################   CAMERAS
  - title: Cameras
    id: cameras
    icon: mdi:cctv
    cards:
      - type: picture-entity
        title: cam1
        entity: camera.cam1
        camera_image: camera.cam1
        show_info: true
        tap_action: dialog
      - type: picture-entity
        title: cam2
        entity: camera.cam2
        camera_image: camera.cam2
        show_info: true
        tap_action: dialog

##################   INFO
  - title: Information
    id: info
    icon: mdi:information
    cards:
      - type: entities
        title: Doorbell settings
        show_header_toggle: false
        entities:
        - input_number.doorbell_volume
        - input_number.doorbell_melody
      - type: entities
        title: Waze
        show_header_toggle: true
        entities:
        - sensor.waze_current_home
        - sensor.waze_current_work
        - sensor.waze_home_work
        - sensor.waze_work_home
      - type: glance
        title: People
        entities:
        - entity: device_tracker.google_maps_111683533988744565132
          name: Dima
        - entity: device_tracker.google_maps_115914092349482836896
          name: Alyona
        - entity: device_tracker.google_maps_117454969161947422882
          name: Yury
      - type: history-graph
        title: People in last 24h
        entities:
        - entity: device_tracker.google_maps_111683533988744565132
          name: Dima
        - entity: device_tracker.google_maps_115914092349482836896
          name: Alyona
        - entity: device_tracker.google_maps_117454969161947422882
          name: Yury
      - type: map
        default_zoom: 15
        entities:
        - device_tracker.google_maps_111683533988744565132
        - device_tracker.google_maps_115914092349482836896
        - device_tracker.google_maps_117454969161947422882

    ##################   FORECAST
  - title: Forecast
    id: forecast
    icon: mdi:cloud
    cards:
      - type: glance
        title: Temperature
        show_header_toggle: true
        entities:
        - sensor.wt00_temperature
        - sensor.wt01_temperature
        - sensor.wt02_temperature
        - sensor.wt03_temperature
        - sensor.wt06_temperature
        - sensor.wt09_temperature
        - sensor.wt12_temperature
        - sensor.wt24_temperature
        - sensor.wt48_temperature
        - sensor.wt72_temperature
      - type: glance
        title: Humidity
        show_header_toggle: true
        entities:
        - sensor.wt00_humidity
        - sensor.wt01_humidity
        - sensor.wt02_humidity
        - sensor.wt03_humidity
        - sensor.wt06_humidity
        - sensor.wt09_humidity
        - sensor.wt12_humidity
        - sensor.wt24_humidity
        - sensor.wt48_humidity
        - sensor.wt72_humidity
      - type: glance
        title: Precipitation
        show_header_toggle: true
        entities:
        - sensor.wt00_precipitation
        - sensor.wt01_precipitation
        - sensor.wt02_precipitation
        - sensor.wt03_precipitation
        - sensor.wt06_precipitation
        - sensor.wt09_precipitation
        - sensor.wt12_precipitation
        - sensor.wt24_precipitation
        - sensor.wt48_precipitation
        - sensor.wt72_precipitation
      - type: glance
        title: Wind speed
        show_header_toggle: true
        entities:
        - sensor.wt00_wind_speed
        - sensor.wt01_wind_speed
        - sensor.wt02_wind_speed
        - sensor.wt03_wind_speed
        - sensor.wt06_wind_speed
        - sensor.wt09_wind_speed
        - sensor.wt12_wind_speed
        - sensor.wt24_wind_speed
        - sensor.wt48_wind_speed
        - sensor.wt72_wind_speed
      - type: glance
        title: Pressure
        show_header_toggle: true
        entities:
        - sensor.wt00_pressure
        - sensor.wt01_pressure
        - sensor.wt02_pressure
        - sensor.wt03_pressure
        - sensor.wt06_pressure
        - sensor.wt09_pressure
        - sensor.wt12_pressure
        - sensor.wt24_pressure
        - sensor.wt48_pressure
        - sensor.wt72_pressure
      - type: glance
        title: Outside
        show_header_toggle: true
        show_state: false
        entities:
        - sensor.wt00_symbol
        - sensor.wt01_symbol
        - sensor.wt02_symbol
        - sensor.wt03_symbol
        - sensor.wt06_symbol
        - sensor.wt09_symbol
        - sensor.wt12_symbol
        - sensor.wt24_symbol
        - sensor.wt48_symbol
        - sensor.wt72_symbol
      - type: picture
        image: https://www.yr.no/place/Latvia/Riga/Riga/meteogram.png

##################   SUM
  - title: Summary
    id: sum
    icon: mdi:elephant
    cards:
    - type: custom:monster-card
      card:
        type: entities
        title: Binary Sensors
      filter:
        include:
        - domain: binary_sensor
    - type: custom:monster-card
      card:
        type: entities
        title: Lights
      filter:
        include:
        - domain: light
    - type: custom:monster-card
      card:
        type: entities
        title: Input numbers
      filter:
        include:
        - domain: input_number
        - domain: input_select
        - domain: input_boolean

    - type: custom:monster-card
      card:
        type: entities
        title: Sensors
      filter:
        exclude:
        - entity_id: "sensor.wt*"
        include:
        - domain: sensor
    - type: custom:monster-card
      card:
        type: entities
        title: Automations
      filter:
        include:
        - domain: automation
    - type: custom:monster-card
      card:
        type: entities
        title: Scripts
      filter:
        include:
        - domain: script
    - type: custom:monster-card
      card:
        type: entities
        title: Switches
      filter:
        include:
        - domain: switch

##################   SYSTEM
  - title: System
    id: sys
    icon: mdi:desktop-tower
    cards:
      - type: entities
        title: Date and time
        show_header_toggle: true
        entities:
        - sensor.date
        - sensor.time
        - sensor.days_in_month
      - type: entities
        title: System state
        show_header_toggle: true
        entities:
        - sensor.uptime
        - sensor.processor_use
        - sensor.memory_use_percent
        - sensor.memory_use
        - sensor.memory_free
        - sensor.homeassistant_v2db
        - counter.syslog_warning
        - counter.syslog_error
      - type: entities
        title: System scripts
        show_header_toggle: false
        entities:
        - script.sys_recorder_purge
        - script.sys_recorder_purge_repack
        - script.sys_homeassistant_restart
        - script.sys_logic_reload
      - type: custom:monster-card
        card:
          type: entities
          title: Batteries
        filter:
          include:
          - entity_id: "sensor.*_battery_level"
      - type: entities
        title: Remote
        show_header_toggle: true
        entities:
        - script.sys_sleep_computer
        - script.sys_sleep_laptop
#      - type: custom:tracker-card
#        title:
#        trackers:
#        - sensor.custom_card_tracker
#        - sensor.custom_component_tracker
