- alias: "light_bathroom_turn_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e52779_occupancy
      to: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d00022391ec

- alias: "light_bathroom_turn_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e52779_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d00022391ec