- alias: "door_entrance_opened_too_long"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00024367c8_contact
      from: "off"
      to: "on"
      for:
        minutes: 3
  action:
    - service: script.alarm_door

- alias: "door_entrance_opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00024367c8_contact
      from: "off"
      to: "on"
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F512 Door is opened {{ states['sensor.door_duration_min'].state_with_unit }}"
    - service: script.input_datetime_set_now_door

- alias: "door_entrance_closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00024367c8_contact
      from: "on"
      to: "off"
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F512 Door is closed {{ states['sensor.door_duration_sec'].state_with_unit }}"
    - service: script.input_datetime_set_now_door

- alias: "door_balcony_opened_timer_idle"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000446fa53_contact
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: timer.balcony_session
      state: "idle"
  action:
    - service: timer.start
      entity_id: timer.balcony_session
    - service: counter.increment
      entity_id: counter.balcony_sessions
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001f6ad Session started. Today: {{ states['counter.balcony_sessions'].state }}"
        inline_keyboard:
          - "\U000026d4 Noooooo:/no_balcony_session, \U0000267B Dismiss:/dismiss"
