- alias: "doorbell_single_action"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00021350ee_action
      to: "single"
  action:
    - service: script.doorbell_single
    - service: notify.telegram_all
      data:
        message: "{{ states('sensor.now_hm') }} 🔔 Doorbell single click"

- alias: "doorbell_double_action"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00021350ee_action
      to: "double"
  action:
    - service: script.doorbell_double
    - service: notify.telegram_all
      data:
        message: "{{ states('sensor.now_hm') }} 🔔 Doorbell double click"