- alias: "door_entrance_opened_too_long"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      to: "on"
      for:
        minutes: 3
  action:
    - service: script.alarm_door

- alias: "door_entrance_opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      to: "on"
  action:
    - service: script.aqara_stop_ringtone
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F513 Door is opened ({{ states.sensor.state_change_door_ago_min.state_with_unit }})"
    - service: script.state_change_update_door

- alias: "door_entrance_closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      to: "off"
  action:
    - service: script.aqara_stop_ringtone
    - service: notify.telegram_dima
      data_template:
        message: "{{ states.sensor.now_hm.state }} \U0001F512 Door is closed ({{ states.sensor.state_change_door_ago_sec.state_with_unit }})"
    - service: script.state_change_update_door