- alias: "alert_entrance_door_opened_too_long"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      to: "on"
      for:
        minutes: 2
  action:
    - service: script.alarm_door

- alias: "entrance_door_opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      to: "on"
  action:
    - service: notify.telegram_dima
      data_template:
        message: "{{ now().strftime('%H:%M') }} \U0001F513 Door is opened ({{ ((now() - strptime(states.input_text.state_change_door.state, '%Y%m%d%H%M%S').astimezone()).seconds /60) | round(0)}} min)"
    - service: script.state_change_update_door

- alias: "entrance_door_closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00024367c8
      to: "off"
  action:
    - service: script.aqara_stop_ringtone
    - service: automation.turn_off
      entity_id:
      - automation.entrance_door_opened_too_long_alarm
    - service: notify.telegram_dima
      data_template:
        message: "{{ now().strftime('%H:%M') }} \U0001F512 Door is closed ({{ (now() - strptime(states.input_text.state_change_door.state, '%Y%m%d%H%M%S').astimezone()).seconds }} sec)"
    - service: script.state_change_update_door