- alias: "entrance_door_opened_too_long"
  initial_state: "on"
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d00024367c8
    to: "on"
    for:
      minutes: 2
  action:
  - service: script.alarm_door

- alias: "entrance_door_opened"
  initial_state: "on"
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d00024367c8
    to: "on"
  action:
  - service: notify.telegram_dima
    data_template:
      message: "{{ now().strftime('%H:%M') }} \U0001F513 Door is opened"

- alias: "entrance_door_closed"
  initial_state: "on"
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d00024367c8
    to: "off"
  action:
  - service: script.aqara_stop_ringtone
  - service: automation.turn_off
    entity_id:
    - automation.entrance_door_opened_too_long_alarm
  - service: notify.telegram_dima
    data_template:
      message: "{{ now().strftime('%H:%M') }} \U0001F512 Door is closed"