- alias: "doorbell_single_click"
  initial_state: "on"
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00021350ee
      click_type: single
  action:
  - service: xiaomi_aqara.play_ringtone
    data_template:
      gw_mac: !secret gw_mac
      ringtone_id: "{{states.input_number.doorbell_melody.state|int}}"
      ringtone_vol: "{{states.input_number.doorbell_volume.state|int}}"
  - service: telegram_bot.send_message
    data_template:
      target: !secret tg_chat_dima
      message: "{{ now().strftime('%H:%M') }} \U0001F514 Doorbell single click"
#  - service: telegram_bot.send_photo
#    data_template:
#      target: !secret tg_chat_dima
#      url: "http://localhost:8123{{states.camera.cam2.attributes.entity_picture}}"
#      caption: "Doorbell camera"
#      inline_keyboard:
#      - "\U0001F504 Refresh:/snap cam1, \U0000267B Dismiss:/dismiss"

- alias: "doorbell_double_click"
  initial_state: "on"
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00021350ee
      click_type: double
  action:
  - service: xiaomi_aqara.play_ringtone
    data_template:
      gw_mac: !secret gw_mac
      ringtone_id: "10002"
      ringtone_vol: "{{states.input_number.doorbell_volume.state|int}}"
  - service: notify.telegram_dima
    data_template:
      message: "{{ now().strftime('%H:%M') }} \U0001F514 Doorbell double click"
#  - service: telegram_bot.send_photo
#    data_template:
#      target: !secret tg_chat_dima
#      url: "http://localhost:8123{{states.camera.cam2.attributes.entity_picture}}"
#      caption: "Doorbell camera"
#      inline_keyboard:
#      - "\U0001F504 Refresh:/snap cam1, \U0000267B Dismiss:/dismiss"


