- alias: "smoke_detected"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0003537bf0_smoke
      to: "on"
  action:
    - service: notify.telegram_all
      data:
        message: "{{ states('sensor.now_hm') }} \U0001f525 Smoke detected!!!"