- alias: "mqtt_publish_outpark_temp_min"
  trigger:
    - platform: state
      entity_id: sensor.temperature_158d00022c7cf2
  condition:
    - condition: template
      value_template: "{{ (trigger.to_state.state | default('0') | float) < (states.sensor.outpark_temp_min.state | default('0') | float) }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/min"
        payload: "{{ trigger.to_state.state }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/min/at"
        payload: "{{ now().strftime('%H:%M') }}"
        retain: true

- alias: "mqtt_publish_outpark_temp_max"
  trigger:
    - platform: state
      entity_id: sensor.temperature_158d00022c7cf2
  condition:
    - condition: template
      value_template: "{{ (trigger.to_state.state | default('0') | float) > (states.sensor.outpark_temp_max.state | default('0') | float) }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/max"
        payload: "{{ trigger.to_state.state }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/max/at"
        payload: "{{ now().strftime('%H:%M') }}"
        retain: true

- alias: "mqtt_publish_outyard_temp_min"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002323783_temperature
  condition:
    - condition: template
      value_template: "{{ (trigger.to_state.state | default('0') | float) < (states.sensor.outyard_temp_min.state | default('0') | float) }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/min"
        payload: "{{ trigger.to_state.state }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/min/at"
        payload: "{{ now().strftime('%H:%M') }}"
        retain: true

- alias: "mqtt_publish_outyard_temp_max"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002323783_temperature
  condition:
    - condition: template
      value_template: "{{ (trigger.to_state.state | default('0') | float) > (states.sensor.outyard_temp_max.state | default('0') | float) }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/max"
        payload: "{{ trigger.to_state.state }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/max/at"
        payload: "{{ now().strftime('%H:%M') }}"
        retain: true