- alias: "mqtt_reset_max_and_min"
  trigger:
  - platform: time
    at: "00:00:05"
  action:
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/min"
      payload: "{{ states.sensor.temperature_158d00022c7cf2.state }}"
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/min/at"
      payload: "-"
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/max"
      payload: "{{ states.sensor.temperature_158d00022c7cf2.state }}"
      retain: true
  - service: mqtt.publish
    data_template:
      topic: "outside/temperature/max/at"
      payload: "-"
      retain: true

- alias: "mqtt_power_reset_hour"
  trigger:
    - platform: time_pattern
      hours: "/1"
  action:
    - service: script.mqtt_publish_zero
      data_template:
        topic: "power/computer/hour"

- alias: "mqtt_power_reset_day"
  trigger:
  - platform: time
    at: "00:00:05"
  action:
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/computer/day"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/kitchen/day"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/router/day"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/tv/day"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/fridge/day"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "bathroom/motions"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "livingroom/motions"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "yuriroom/motions"

- alias: "mqtt_power_reset_week"
  trigger:
  - platform: time
    at: "00:00:15"
  condition:
  - condition: template
    value_template: "{{ now().isoweekday() == 1 }}"
  action:
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/computer/week"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/kitchen/week"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/router/week"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/tv/week"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/fridge/week"

- alias: "mqtt_power_reset_month"
  trigger:
  - platform: time
    at: "00:00:25"
  condition:
  - condition: template
    value_template: "{{ now().day == 1 }}"
  action:
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/computer/month"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/kitchen/month"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/router/month"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/tv/month"
  - service: script.mqtt_publish_zero
    data_template:
      topic: "power/fridge/month"
