- alias: "mqtt_reset_max_and_min"
  trigger:
    - platform: time
      at: "00:00:05"
  action:
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/min"
        payload: "{{ states('sensor.0x00158d00022c7cf2_temperature') }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/min/at"
        payload: "-"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/max"
        payload: "{{ states('sensor.0x00158d00022c7cf2_temperature') }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outpark/temperature/max/at"
        payload: "-"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/min"
        payload: "{{ states('sensor.0x00158d0002323783_temperature') }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/min/at"
        payload: "-"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/max"
        payload: "{{ states('sensor.0x00158d0002323783_temperature') }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "outyard/temperature/max/at"
        payload: "-"
        retain: true