- alias: "weather_meteo_alert"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.lv_kurzeme
        - binary_sensor.lv_vidzeme
        - binary_sensor.lv_zemgale
        - binary_sensor.lv_latgale
  action:
    - service: notify.telegram_dima
      data:
        message: >
          {{ states('sensor.now_hm') }} 🔊 {{ trigger.to_state.attributes.friendly_name }}
          {% if trigger.to_state.state == 'on' %}
          `{{ trigger.to_state.attributes.event }} ({{ trigger.to_state.attributes.certainty }})`
          {{ trigger.to_state.attributes.description }}
          {% else %}
          ✅ Safe!
          {% endif %}

- alias: "airvisual_alert"
  trigger:
    - platform: state
      entity_id: sensor.u_s_air_pollution_level
  action:
    - service: notify.telegram_dima
      data:
        message: "{{ states('sensor.now_hm') }} 🌬️ {{ trigger.from_state.state }} -> {{ trigger.to_state.state }}: {{ states['sensor.u_s_air_quality_index'].state_with_unit}}, {{ states['sensor.u_s_main_pollutant'].state_with_unit}} | #air"

- alias: "kitchen_power_switched_off"
  trigger:
    - platform: state
      entity_id: switch.power_strip_2
      to: "off"
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} ⚡️ Kitchen power strip is off!"
        inline_keyboard:
          - "👍 Turn on:/kitchen_is_off, ♻️ Dismiss:/dismiss"