- alias: "ha_bad_login"
  trigger:
    - platform: state
      entity_id: persistent_notification.httplogin
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state == 'notifying' }}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U00002620 {{ states.persistent_notification.httplogin.attributes.message }}"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"
    - service: persistent_notification.dismiss
      data:
        notification_id: "httplogin"

- alias: "google_cast_updated"
  trigger:
    - platform: state
      entity_id:
        - sensor.cast_version_black_speaker
        - sensor.cast_version_kitchen_display
        - sensor.cast_version_loud_speaker
        - sensor.cast_version_yuri_speaker
        - sensor.cast_version_chromecast
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U00002B06 `{{ trigger.from_state.attributes.friendly_name }}` updated {{ trigger.from_state.state }} -> {{ trigger.to_state.state }}"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"