# - alias: "watcher_state"
#   trigger:
#     - platform: state
#       entity_id:
#         - sensor.latvia_coronavirus_confirmed
#         - sensor.estonia_coronavirus_confirmed
#         - sensor.lithuania_coronavirus_confirmed
#   action:
#     - service: telegram_bot.send_message
#       data_template:
#         target: !secret tg_chat_dima
#         message: "{{ states['sensor.now_hm'].state }} \U00002139 `{{ trigger.from_state.attributes.friendly_name }}`: {{ trigger.from_state.state }} -> {{ trigger.to_state.state }}"
#         inline_keyboard:
#           - "\U0000267B Dismiss:/dismiss"

- alias: "watcher_coronavirus"
  trigger:
    - platform: state
      entity_id:
        - sensor.latvia_coronavirus_confirmed
        - sensor.estonia_coronavirus_confirmed
        - sensor.lithuania_coronavirus_confirmed
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U00002139 `{{ trigger.from_state.attributes.friendly_name }}:` {{ trigger.from_state.state }} -> {{ trigger.to_state.state }} ({{trigger.to_state.state|int - trigger.from_state.state|int}})"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"

- alias: "ha_bad_login"
  trigger:
    - platform: state
      entity_id: persistent_notification.httplogin
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state == 'notifying' }}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U00002620 {{ states.persistent_notification.httplogin.attributes.message }}"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"
    - service: persistent_notification.dismiss
      data:
        notification_id: "httplogin"

- alias: "google_cast_updated"
  trigger:
    - platform: state
      entity_id:
        - sensor.cast_version_black_speaker
        - sensor.cast_version_kitchen_display
        - sensor.cast_version_loud_speaker
        - sensor.cast_version_yuri_speaker
        - sensor.cast_version_chromecast
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states['sensor.now_hm'].state }} \U00002B06 `{{ trigger.from_state.attributes.friendly_name }}` updated {{ trigger.from_state.state }} -> {{ trigger.to_state.state }}"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"