- alias: "ha_start"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U0001F916 {{ states.sensor.ha_version_current.state }} #HA is back online. ({{ states.sensor.rpi.state }})"
        inline_keyboard:
          - "\U0001F532 Menu:/menu, \U0000267B Dismiss:/dismiss"

- alias: "ha_shutdown"
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} \U0001F6D1 {{ states.sensor.ha_version_current.state }} #HA goes offline (uptime {{ (24 * states.sensor.uptime.state | float) | round(2) }} h). ({{ states.sensor.rpi.state }})"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"