- alias: "ha_start"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F916 {{ states('sensor.ha_version_current') }} #HA is back online in {{ states['sensor.start_time'].state_with_unit }}. ({{ states('sensor.rpi') }})"
        inline_keyboard:
          - "\U0001F532 Menu:/menu, \U0000267B Dismiss:/dismiss"

- alias: "ha_shutdown"
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tg_chat_dima
        message: "{{ states('sensor.now_hm') }} \U0001F6D1 {{ states('sensor.ha_version_current') }} #HA goes offline (uptime {{ states['sensor.system_uptime'].state_with_unit }}). ({{ states('sensor.rpi') }})"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"