- alias: "ha_start"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ now().strftime('%H:%M') }} \U0001F916 {{ states.sensor.version_ha_current.state }} #HA back online ({{ ((now() - strptime(states.sensor.state_change_ha.state, '%Y%m%d%H%M%S').astimezone()).seconds /60) | round(2)}} min)"
        inline_keyboard:
        - "\U0001F532 Menu:/menu, \U0000267B Dismiss:/dismiss"
    - service: script.state_change_update_ha

- alias: "ha_shutdown"
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: script.state_change_update_ha
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ now().strftime('%H:%M') }} \U0001F6D1 {{ states.sensor.version_ha_current.state }} #HA goes offline ({{ ((now() - strptime(states.sensor.state_change_ha.state, '%Y%m%d%H%M%S').astimezone()).seconds /60) | round(2)}} min)"
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"

- alias: "ha_bad_login"
  trigger:
    - platform: state
      entity_id: persistent_notification.httplogin
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state == 'notifying' }}"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ now().strftime('%H:%M') }} \U00002620 {{ states.persistent_notification.httplogin.attributes.message }}"
        inline_keyboard:
        - "\U0000267B Dismiss:/dismiss"
    - service: persistent_notification.dismiss
      data:
        notification_id: "httplogin"