- alias: "weather_vidzeme_alert"
  trigger:
    - platform: state
      entity_id: binary_sensor.lv_vidzeme
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: >
          {{ states.sensor.now_hm.state }} \U00002139 Vidzeme

          {% if is_state('binary_sensor.lv_vidzeme', 'on')  %}
            {{ '\U0001f321' }} {{ states.binary_sensor.lv_vidzeme.attributes.event }} ({{ states.binary_sensor.lv_vidzeme.attributes.certainty }})
            {{ states.binary_sensor.lv_vidzeme.attributes.description }}  
          {% else %}
            {{ '\U00002705' }} Safe!
          {% endif %}
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"

- alias: "weather_kurzeme_alert"
  trigger:
    - platform: state
      entity_id: binary_sensor.lv_kurzeme
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: >
          {{ states.sensor.now_hm.state }} \U00002139 Kurzeme
          
          {% if is_state('binary_sensor.lv_kurzeme', 'on')  %}
            {{ '\U0001f321' }} {{ states.binary_sensor.lv_kurzeme.attributes.event }} ({{ states.binary_sensor.lv_kurzeme.attributes.certainty }})
            {{ states.binary_sensor.lv_kurzeme.attributes.description }}  
          {% else %}
            {{ '\U00002705' }} Safe!
          {% endif %}
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"