- alias: "weather_vidzeme_alert"
  trigger:
    - platform: state
      entity_id: binary_sensor.lv_vidzeme
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: >
          {{ states.sensor.now_hm.state }} {{ '\U00002139' }} Vidzeme
          {% if is_state('binary_sensor.lv_vidzeme', 'on')  %}
          `{{ states.binary_sensor.lv_vidzeme.attributes.event }} ({{ states.binary_sensor.lv_vidzeme.attributes.certainty }})`
          {{ states.binary_sensor.lv_vidzeme.attributes.description }}
          {% else %}
          {{ '\U00002705' }} Safe!
          {% endif %}
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"

- alias: "weather_kurzeme_alert"
  trigger:
    - platform: state
      entity_id: binary_sensor.lv_kurzeme
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: >
          {{ states.sensor.now_hm.state }} {{ '\U00002139' }} Kurzeme
          {% if is_state('binary_sensor.lv_kurzeme', 'on')  %}
          `{{ states.binary_sensor.lv_kurzeme.attributes.event }} ({{ states.binary_sensor.lv_kurzeme.attributes.certainty }})`
          {{ states.binary_sensor.lv_kurzeme.attributes.description }}
          {% else %}
          {{ '\U00002705' }} Safe!
          {% endif %}
        inline_keyboard:
          - "\U0000267B Dismiss:/dismiss"

- alias: "kitchen_power_switched_off"
  trigger:
    - platform: state
      entity_id: switch.power_strip_2
      to: "off"
  action:
    - service: telegram_bot.send_message
      data_template:
        target: !secret tg_chat_dima
        message: "{{ states.sensor.now_hm.state }} {{ '\U000026a1' }} Kitchen power strip is off!"
        inline_keyboard:
          - "\U0001F4A4 Turn on:/power_strip_2_on, \U0000267B Dismiss:/dismiss"