- alias: "main_max_reset"
  trigger:
    - platform: time
      at: "00:00:05"
  action:
    - service: input_number.set_value
      data:
        entity_id: 
          - input_number.outdoor_temperature_min
          - input_number.outdoor_temperature_max
        value: "{{ states('sensor.outdoor_temperature') | float }}"
    - service: input_number.set_value
      data:
        entity_id: 
          - input_number.park_temperature_min
          - input_number.park_temperature_max
        value: "{{ states('sensor.0x00158d00022c7cf2_temperature') | float }}"
