# UPDATE NUMBERS
- alias: "update_outdoor_temperature_min_number"
  trigger:
    - platform: state
      entity_id: sensor.outdoor_temperature_min
  condition: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.outdoor_temperature_min
        value: "{{ trigger.to_state.state | float }}"

- alias: "update_outdoor_temperature_max_number"
  trigger:
    - platform: state
      entity_id: sensor.outdoor_temperature_max
  condition: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.outdoor_temperature_max
        value: "{{ trigger.to_state.state | float }}"

- alias: "update_park_temperature_min_number"
  trigger:
    - platform: state
      entity_id: sensor.park_temperature_min
  condition: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.park_temperature_min
        value: "{{ trigger.to_state.state | float }}"

- alias: "update_park_temperature_max_number"
  trigger:
    - platform: state
      entity_id: sensor.park_temperature_max
  condition: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.park_temperature_max
        value: "{{ trigger.to_state.state | float }}"

#UPDATE DT BY NUMBERS
- alias: "update_outdoor_temperature_min_dt"
  trigger:
    - platform: state
      entity_id: input_number.outdoor_temperature_min
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.outdoor_temperature_min

- alias: "update_outdoor_temperature_max_dt"
  trigger:
    - platform: state
      entity_id: input_number.outdoor_temperature_max
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.outdoor_temperature_max

- alias: "update_park_temperature_min_dt"
  trigger:
    - platform: state
      entity_id: input_number.park_temperature_min
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.park_temperature_min

- alias: "update_park_temperature_max_dt"
  trigger:
    - platform: state
      entity_id: input_number.park_temperature_max
  action:
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.park_temperature_max