- alias: "main_max_reset"
  trigger:
    - platform: time
      at: "00:00:05"
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.outdoor_temperature_min
        value: "{{ states['sensor.outdoor_temperature'].state | float }}"
    - service: input_number.set_value
      data:
        entity_id: input_number.outdoor_temperature_max
        value: "{{ states['sensor.outdoor_temperature'].state | float }}"

    - service: input_number.set_value
      data:
        entity_id: input_number.outpark_temperature_min
        value: "{{ states['sensor.0x00158d00022c7cf2_temperature'].state | float }}"
    - service: input_number.set_value
      data:
        entity_id: input_number.outpark_temperature_max
        value: "{{ states['sensor.0x00158d00022c7cf2_temperature'].state | float }}"
    - service: input_number.set_value
      data:
        entity_id: input_number.outyard_temperature_min
        value: "{{ states['sensor.0x00158d0002323783_temperature'].state | float }}"
    - service: input_number.set_value
      data:
        entity_id: input_number.outyard_temperature_max
        value: "{{ states['sensor.0x00158d0002323783_temperature'].state | float }}"

    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.outpark_temperature_min_at
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.outpark_temperature_max_at
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.outyard_temperature_min_at
    - service: script.input_datetime_set_now
      data:
        entity_id: input_datetime.outyard_temperature_max_at
