- alias: "light_bathroom_turn_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e52779_occupancy
      to: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d00022391ec_switch_right

- alias: "light_bathroom_turn_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e52779_occupancy
      to: "off"
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d00022391ec_switch_right

- alias: "light_bathroom_turn_off_aftermath"
  trigger:
    - platform: state
      entity_id: light.bathroom
      from: "on"
      to: "off"
  action:
    - service: script.radio_bathroom_stop

- alias: "light_bathroom_turn_on_aftermath"
  trigger:
    - platform: state
      entity_id: light.bathroom
      from: "off"
      to: "on"
  action:
    - service: script.radio_bathroom_start