- alias: "light_ball_on"
  trigger:
    - platform: time
      at: "19:00:00"
  action:
    - service: light.turn_on
      entity_id: light.bulb_s

- alias: "light_ball_off"
  trigger:
    - platform: time
      at: "22:00:00"
  action:
    - service: light.turn_off
      entity_id: light.bulb_s
