- alias: "light_small_torch_turn_off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00026b96c1
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00026b96c1
        click_type: single
  condition:
    condition: state
    entity_id: light.small_torch
    state: "on"
  action:
    - service: light.turn_off
      entity_id: light.small_torch

- alias: "light_small_torch_turn_on_max"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00026b96c1
        click_type: single
  condition:
    condition: state
    entity_id: light.small_torch
    state: "off"
  action:
    - service: script.turn_on
      entity_id: script.light_small_torch_turn_on_max

- alias: "light_small_torch_turn_on_min"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00026b96c1
        click_type: single
  condition:
    condition: state
    entity_id: light.small_torch
    state: "off"
  action:
    - service: script.turn_on
      entity_id: script.light_small_torch_turn_on_min

- alias: "light_livingroom_turn_off"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "single"
  condition:
    - condition: state
      entity_id: light.livingroom_color
      state: "on"
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_off

- alias: "light_livingroom_turn_on"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "single"
  condition:
    - condition: state
      entity_id: light.livingroom_color
      state: "off"
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_on_default

- alias: "light_livroom_color_flow"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "double"
  action:
    - service: script.light_livingroom_color_flow