- alias: "light_livingroom_turn_off"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "single"
  condition:
    - condition: state
      entity_id: light.livingroom
      state: "on"
  action:
    - service: script.light_livingroom_turn_off

- alias: "light_livingroom_turn_on"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "single"
  condition:
    - condition: state
      entity_id: light.livingroom
      state: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.light_livingroom_turn_on_def

- alias: "light_livroom_double"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "double"
  action:
    - service: switch.turn_on
      entity_id: switch.circadian_lighting_circadian_lighting
    - service: script.light_livingroom_turn_on_min

- alias: "pendant_switch_click_on"
  trigger:
    - platform: state
      entity_id: sensor.0xec1bbdfffea090e5_click
      # to: "on"
  action:
    - service: light.toggle
      entity_id: light.standalone_switch

# - alias: "pendant_switch_click_off"
#   trigger:
#     - platform: state
#       entity_id: sensor.0xec1bbdfffea090e5_click
#       to: "off"
#   action:
#     - service: light.toggle
#       entity_id: light.standalone_switch

# - alias: "pendant_switch_brightness_up"
#   trigger:
#     - platform: state
#       entity_id: sensor.0xec1bbdfffea090e5_click
#       to: "brightness_up"
#   action:
#     - service: script.light_adjust_brightness
#       data_template:
#         entity_id: light.0xec1bbdfffe4d16eb_light
#         step: 51

# - alias: "pendant_switch_brightness_down"
#   trigger:
#     - platform: state
#       entity_id: sensor.0xec1bbdfffea090e5_click
#       to: "brightness_down"
#   action:
#     - service: script.light_adjust_brightness
#       data_template:
#         entity_id: light.0xec1bbdfffe4d16eb_light
#         step: -51