- alias: "light_livingroom_turn_off"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "single"
  condition:
    - condition: state
      entity_id: light.livingroom_color
      state: "on"
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_off

- alias: "light_livingroom_turn_on"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0002136276_click
      to: "single"
  condition:
    - condition: state
      entity_id: light.livingroom_color
      state: "off"
  action:
    - service: script.turn_on
      entity_id: script.light_livingroom_turn_on_default

- alias: "ikea_switch_1_click_on"
  trigger:
    - platform: state
      entity_id: sensor.0xec1bbdfffea090e5_click
      to: "on"
  action:
    - service: light.toggle
      entity_id: light.0xec1bbdfffe4d16eb_light

- alias: "ikea_switch_1_click_off"
  trigger:
    - platform: state
      entity_id: sensor.0xec1bbdfffea090e5_click
      to: "off"
  action:
    - service: light.toggle
      entity_id: light.standalone_switch

- alias: "ikea_switch_1_brightness_up"
  trigger:
    - platform: state
      entity_id: sensor.0xec1bbdfffea090e5_click
      to: "brightness_up"
  action:
    - service: script.light_adjust_brightness
      data_template:
        entity_id: light.0xec1bbdfffe4d16eb_light
        step: 51

- alias: "ikea_switch_1_brightness_down"
  trigger:
    - platform: state
      entity_id: sensor.0xec1bbdfffea090e5_click
      to: "brightness_down"
  action:
    - service: script.light_adjust_brightness
      data_template:
        entity_id: light.0xec1bbdfffe4d16eb_light
        step: -51