- alias: "storage_switch_actions"
  trigger:
    - platform: state
      entity_id: sensor.0x14b457fffe8085df_action
      to: "on"
    - platform: state
      entity_id: sensor.0x14b457fffe8085df_action
      to: "off"
  action:
    - service: light.toggle
      entity_id: light.0x14b457fffe4dc1c2_light

- alias: "storage_switch_brightness_up"
  trigger:
    - platform: state
      entity_id: sensor.0x14b457fffe8085df_action
      to: "brightness_up"
  action:
    - service: script.light_adjust_brightness
      data:
        entity_id: light.0x14b457fffe4dc1c2_light
        step: 51

- alias: "storage_switch_brightness_down"
  trigger:
    - platform: state
      entity_id: sensor.0x14b457fffe8085df_action
      to: "brightness_down"
  action:
    - service: script.light_adjust_brightness
      data:
        entity_id: light.0x14b457fffe4dc1c2_light
        step: -51

- alias: "storage_turn_off_light"
  trigger:
    - platform: state
      entity_id: light.0x14b457fffe4dc1c2_light
      to: "on"
      for:
        minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.0x14b457fffe4dc1c2_light
