- alias: "workday_wakeup"
  trigger:
    - platform: time
      at: input_datetime.workday_morning_wakeup
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_wakeup
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_display
        volume_level: 0.2
    - service: script.media_radio_play_param_cast
      data:
        entity_id: media_player.kitchen_display
        media_content_id: "http://icecast.vgtrk.cdnvideo.ru/moscowfm128"

- alias: "workday_ready"
  trigger:
    - platform: time
      at: input_datetime.workday_morning_ready
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_ready

- alias: "workday_go"
  trigger:
    - platform: time
      at: input_datetime.workday_morning_go
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_go

- alias: "workday_gone"
  trigger:
    - platform: time
      at: input_datetime.workday_morning_gone
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_gone

- alias: "workday_computer_off"
  trigger:
    - platform: time
      at: "07:33:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
  action:
    - service: script.rmt_computer_sleep
