- alias: "workday_init"
  trigger:
    - platform: time
      at: "06:55:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_init
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_display
        volume_level: 0.2
    - service: script.media_radio_play_param_cast
      data:
        entity_id: media_player.kitchen_display
        media_content_id: "http://icecast.vgtrk.cdnvideo.ru/moscowfm128"

- alias: "workday_ready_1"
  trigger:
    - platform: time
      at: "07:25:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_ready_1

- alias: "workday_ready_2"
  trigger:
    - platform: time
      at: "07:27:30"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_ready_2

- alias: "workday_steady"
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_steady

- alias: "workday_scene_go"
  trigger:
    - platform: time
      at: "07:35:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_go

- alias: "workday_scene_terminate"
  trigger:
    - platform: time
      at: "07:45:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
  action:
    - service: script.workday_terminate

- alias: "workday_computer_off"
  trigger:
    - platform: time
      at: "07:33:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_morning_activity
      state: "on"
    - condition: state
      entity_id: binary_sensor.ping_computer
      state: "on"
  action:
    - service: script.rmt_computer_sleep
