- alias: "light_small_torch_turn_off"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00026b96c1_click
      to: "left"
    - platform: state
      entity_id: sensor.0x00158d00026b96c1_click
      to: "right"
  condition:
    condition: state
    entity_id: light.small_torch
    state: "on"
  action:
    - service: light.turn_off
      entity_id: light.small_torch

- alias: "light_small_torch_turn_on_max"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00026b96c1_click
      to: "right"
  condition:
    condition: state
    entity_id: light.small_torch
    state: "off"
  action:
    - service: script.turn_on
      entity_id: script.light_small_torch_turn_on_max

- alias: "light_small_torch_turn_on_min"
  trigger:
    - platform: state
      entity_id: sensor.0x00158d00026b96c1_click
      to: "left"
  condition:
    condition: state
    entity_id: light.small_torch
    state: "off"
  action:
    - service: script.turn_on
      entity_id: script.light_small_torch_turn_on_min