- alias: "telega_callback_no_balcony_session"
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/no_balcony_session"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Roger {{ trigger.event.data.data }}"
    - service: timer.cancel
      entity_id: timer.balcony_session
    - service: telegram_bot.delete_message
      data_template:
        chat_id: "{{ trigger.event.data.chat_id }}"
        message_id: "{{ trigger.event.data.message.message_id }}"
    - condition: numeric_state
      entity_id: counter.balcony_sessions
      above: 0
    - service: counter.decrement
      entity_id: counter.balcony_sessions

