- alias: "telega_callback_menu"
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/menu"
  action:
    - service: telegram_bot.answer_callback_query
      data:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Roger {{ trigger.event.data.data }}"
    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "Main menu"
        inline_keyboard:
          - "🌤️ Environment:/environment, 👪 People:/people"
          - "🚧 Tech:/tech, ♻️ Dismiss:/dismiss"

- alias: "telega_callback_dismiss"
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: "/dismiss"
  action:
    - service: telegram_bot.answer_callback_query
      data:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Roger {{ trigger.event.data.data }}"
    - service: telegram_bot.delete_message
      data:
        chat_id: "{{ trigger.event.data.chat_id }}"
        message_id: "{{ trigger.event.data.message.message_id }}"