- alias: "telega_text_M"
  trigger:
    - platform: event
      event_type: telegram_text
      event_data:
        text: "m"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "M"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "ь"
  action:
    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "Main menu"
        inline_keyboard:
          - "🌤️ Environment:/environment, 👪 People:/people"
          - "🚧 Tech:/tech, ♻️ Dismiss:/dismiss"

- alias: "telega_text_L"
  trigger:
    - platform: event
      event_type: telegram_text
      event_data:
        text: "l"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "L"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "д"
  action:
    - service: telegram_bot.send_document
      data:
        target: "{{ trigger.event.data.user_id }}"
        file: "/config/home-assistant.log"
        inline_keyboard:
          - "♻️ Dismiss:/dismiss"

- alias: "telega_text_R"
  trigger:
    - platform: event
      event_type: telegram_text
      event_data:
        text: "r"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "R"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "к"
  action:
    - service: homeassistant.restart

- alias: "telega_text_P"
  trigger:
    - platform: event
      event_type: telegram_text
      event_data:
        text: "p"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "P"
    - platform: event
      event_type: telegram_text
      event_data:
        text: "з"
  action:
    - service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.user_id }}"
        message: "Select person to check"
        inline_keyboard:
          - "👨 Dima:/tracker dima, 👩 Alyona:/tracker alyona"
          - "👦 Yury:/tracker yury, 👧 Elisa:/tracker elisa"
          - "♻️ Dismiss:/dismiss"