dev_media_extractor:
  sequence:
  - service: media_extractor.play_media
    entity_id: media_player.kodi
    data:
      media_content_id: "https://www.youtube.com/watch?v=w4LkSRXrK34"
      media_content_type: VIDEO

dev_telega_direct:
  sequence:
  - service: telegram_bot.send_message
    data_template:
      target: !secret tg_chat
      message: "{{ now().strftime('%H:%M') }} dev_telega_direct"

dev_telega_notify:
  sequence:
  - service: notify.telegram_dima
    data_template:
      message: "{{ now().strftime('%H:%M') }} dev_telega_direct"