- alias: "ha_sch_snapshot_create"
  condition:
    - condition: state
      entity_id: binary_sensor.is_backup_day
      state: "on"
  trigger:
    - platform: time
      at: "01:15:00"
  action:
    - service: script.ha_snapshot_full_create

- alias: "ha_sch_snapshot_to_gdrive"
  condition:
    - condition: state
      entity_id: binary_sensor.is_backup_day
      state: "on"
  trigger:
    - platform: time
      at: "03:30:00"
  action:
    - service: rest_command.google_backup