- alias: "light_cosiness_on"
  trigger:
#    - platform: time
#      at: "17:00:00"
    - platform: sun
      event: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.cosiness_on

- alias: "light_cosiness_off"
  trigger:
  - platform: time
    at: "23:59:00"
  action:
    - service: scene.turn_on
      entity_id: scene.cosiness_off