- alias: "schedule_power_strip_computer_off"
  initial_state: "on"
  trigger:
  - platform: time
    at: "02:00:00"
  action:
  - service: switch.turn_off
    entity_id: switch.power_strip_1

- alias: "schedule_power_strip_computer_on"
  initial_state: "on"
  trigger:
  - platform: time
    at: "06:50:00"
  action:
  - service: switch.turn_on
    entity_id: switch.power_strip_1

- alias: "saving_computer_is_off_for_a_while"
  initial_state: "on"
  trigger:
  - platform: state
    entity_id: binary_sensor.computer
    from: "on"
    to: "off"
    for:
      minutes: 10
  action:
  - service: notify.telegram_dima
    data_template:
      message: "{{ now().strftime('%H:%M') }} Computer was turned off 10 minutes ago"
