######################## GARLAND
- alias: "light_off_after_sunset"
  initial_state: "on"
  trigger:
  - platform: time
    at: "23:00:00"
  - platform: sun
    event: sunset
    offset: '04:00:00'
  action:
  - service: script.light_turn_off_entrance_garland

- alias: "light_on_at_the_sunset"
  initial_state: "on"
  trigger:
    platform: sun
    event: sunset
  action:
  - service: script.light_turn_on_entrance_garland

######################## LIVING ROOM @ WORKDAY
- alias: "light_at_working_day_on"
  initial_state: "on"
  trigger:
    platform: time
    at: "06:50:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
    - service: script.light_turn_on_livingroom_torch_by_params
    - service: script.light_turn_on_livingroom_corner_by_params
    - service: script.light_turn_on_entrance_garland

- alias: "light_at_working_day_off"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:45:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
    - service: script.light_turn_off_livingroom
    - service: script.light_turn_off_entrance_garland

######################## LIVING ROOM @ WORKDAY (GREEN->ORANGE->RED)

- alias: "light_at_working_day_ready_1"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:25:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.livingroom_ambient
      hs_color: [ 130, 100 ]

- alias: "light_at_working_day_ready_2"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:27:30"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.livingroom_ambient
      hs_color: [ 130, 100 ]

- alias: "light_at_working_day_steady"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:30:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.livingroom_ambient
      hs_color: [ 30, 100 ]
  - service: script.sys_sleep_computer

- alias: "light_at_working_day_go"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:35:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.livingroom_ambient
      hs_color: [ 350, 100 ]
