- alias: "telegram_send_outside"
  initial_state: "on"
  trigger:
  - platform: time
    at: "06:55:00"
  - platform: time
    at: "23:55:00"
  action:
  - service: script.telegram_send_outside
    data_template:
      target: !secret tg_chat_dima

- alias: "telegram_send_electro"
  initial_state: "on"
  trigger:
  - platform: time
    at: "23:59:00"
  action:
  - service: script.telegram_send_electro
    data_template:
      target: !secret tg_chat_dima

#- alias: "schedule_day_begins"
#  initial_state: "on"
#  trigger:
#  - platform: time
#    at: "00:00:02"
#  action:
#  - service: homeassistant.update_entity
#    entity_id:
#    - sensor.is_workday