- alias: "schedule_daily_refresh"
  initial_state: "on"
  trigger:
  - platform: time
    at: "00:00:01"
  action:
  - service: homeassistant.update_entity
    entity_id:
    - sensor.is_workday


- alias: "schedule_daily_sets"
  initial_state: "on"
  trigger:
    - platform: time
      at: "00:00:05"
  action:
  - service: input_number.set_value
    entity_id: input_number.computer_today_allowed
    data_template:
      value: >
        {% if is_state('sensor.is_workday', 'True') %}
          300
        {% else %}
          500
        {% endif %}