- alias: "schedule_daily_refresh"
  trigger:
    - platform: time
      at: "00:00:01"
  action:
    - service: homeassistant.update_entity
      entity_id:
        - sensor.is_workday

- alias: "schedule_daily_sets"
  trigger:
    - platform: time
      at: "00:00:05"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.computer_today_limit
    - service: input_number.set_value
      entity_id: input_number.computer_today_allowed
      data_template:
        value: >
          {% if is_state('sensor.is_workday', 'True') %}
            300
          {% else %}
            500
          {% endif %}

#- alias: "schedule_circadian_on"
#  trigger:
#    - platform: time
#      at: "16:00:00"
#  action:
#    - service: switch.turn_on
#      entity_id: switch.circadian_lighting_circadian_lighting
#
#- alias: "schedule_circadian_off"
#  trigger:
#    - platform: time
#      at: "00:05:00"
#  action:
#    - service: switch.turn_off
#      entity_id: switch.circadian_lighting_circadian_lighting

- alias: "schedule_backups_to_dropbox"
  trigger:
    - platform: time
      at: "00:05:00"
  action:
    - service: hassio.addon_stdin
      data:
        addon: "7be23ff5_dropbox_sync"
        input: {"command":"upload"}