- alias: "good_morning"
  trigger:
    - platform: time
      at: "06:45:00"
  action:
    - service: script.turn_on
      entity_id: script.good_morning

- alias: "light_cosiness_on"
  trigger:
#    - platform: time
#      at: "17:00:00"
    - platform: sun
      event: sunset
  action:
    - service: script.turn_on
      entity_id: script.cosiness_on

- alias: "light_cosiness_off"
  trigger:
    - platform: time
      at: "23:59:00"
  action:
    - service: script.turn_on
      entity_id: script.cosiness_off