- alias: "reset_counters"
  trigger:
    - platform: time
      at: "00:00:01"
  action:
    - service: counter.reset
      entity_id: 
        - counter.balcony_sessions
        - counter.doorbell
        - counter.rpi_disconnect
        - counter.yuryroom_motions_watch

- alias: "refresh_abox_temp"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  action:
    - service: script.androidbox_refresh_temp