- alias: "telegram_send_outside_dima"
  trigger:
    - platform: time
      at: "06:55:00"
    - platform: time
      at: "23:55:00"
  action:
    - service: script.telegram_send_outside
      data_template:
        target: !secret tg_chat_dima

- alias: "telegram_send_outside_alyona"
  trigger:
    - platform: time
      at: "07:30:00"
  action:
    - service: script.telegram_send_outside
      data_template:
        target: !secret tg_chat_alyona

- alias: "telegram_send_electro"
  trigger:
    - platform: time
      at: "23:59:00"
  action:
    - service: script.telegram_send_electro
      data_template:
        target: !secret tg_chat_dima