- alias: "working_day_scene_on"
  trigger:
    - platform: time
      at: "06:55:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_init
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen_display
        volume_level: 0.2
    - service: script.media_radio_play_param_cast
      data_template:
        entity_id: media_player.kitchen_display
        media_content_id: "http://ice.stream.frequence3.net/frequence3-128.mp3"

- alias: "working_day_scene_ready_1"
  trigger:
    - platform: time
      at: "07:25:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_ready_1
    - service: script.tts_summary

- alias: "working_day_scene_ready_2"
  trigger:
    - platform: time
      at: "07:27:30"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_ready_2

- alias: "working_day_scene_at_steady"
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_steady

- alias: "working_day_computer_off"
  trigger:
    - platform: time
      at: "07:33:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: script.rmt_computer_sleep

- alias: "working_day_scene_go"
  trigger:
    - platform: time
      at: "07:35:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_go

- alias: "working_day_scene_terminate"
  trigger:
    - platform: time
      at: "07:45:00"
  condition:
    - condition: state
      entity_id: binary_sensor.is_workday
      state: "on"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_terminate
