- alias: "working_day_light_on"
  initial_state: "on"
  trigger:
  - platform: time
    at: "06:55:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    entity_id: light.group_morning_core
    data_template:
      brightness: "20"
      color_temp: "500"
      transition: "20"
  - service: script.light_turn_on_entrance_garland

- alias: "working_day_light_ready_1"
  initial_state: "on"
  trigger:
  - platform: time
    at: "07:25:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    entity_id: light.group_morning
    data_template:
      hs_color: [ 100, 100 ]
  - service: script.tts_summary

- alias: "working_day_light_ready_2"
  initial_state: "on"
  trigger:
  - platform: time
    at: "07:27:30"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    entity_id: light.group_morning
    data_template:
      hs_color: [ 60, 100 ]

- alias: "working_day_light_at_steady"
  initial_state: "on"
  trigger:
  - platform: time
    at: "07:30:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    entity_id: light.group_morning
    data_template:
      hs_color: [ 30, 100 ]

- alias: "working_day_computer_off"
  initial_state: "on"
  trigger:
  - platform: time
    at: "07:33:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: script.rmt_computer_sleep

- alias: "working_day_light_go"
  initial_state: "on"
  trigger:
  - platform: time
    at: "07:35:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_on
    entity_id: light.group_morning
    data_template:
      hs_color: [ 0, 100 ]

- alias: "working_day_light_off"
  initial_state: "on"
  trigger:
  - platform: time
    at: "07:45:00"
  condition:
  - condition: state
    entity_id: sensor.is_workday
    state: "True"
  action:
  - service: light.turn_off
    entity_id: light.group_morning
  - service: switch.turn_off
    entity_id: switch.wall_plug_158d0002013f1e