- alias: "working_day_scene_on"
  trigger:
    - platform: time
      at: "06:55:00"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_init

- alias: "working_day_scene_ready_1"
  trigger:
    - platform: time
      at: "07:25:00"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_ready_1
    - service: script.tts_summary

- alias: "working_day_scene_ready_2"
  trigger:
    - platform: time
      at: "07:27:30"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_ready_2

- alias: "working_day_scene_at_steady"
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_steady

- alias: "working_day_computer_off"
  trigger:
    - platform: time
      at: "07:33:00"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: script.rmt_computer_sleep

- alias: "working_day_scene_go"
  trigger:
    - platform: time
      at: "07:35:00"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_go

- alias: "working_day_scene_terminate"
  trigger:
    - platform: time
      at: "07:45:00"
  condition:
    - condition: state
      entity_id: sensor.is_workday
      state: "True"
  action:
    - service: scene.turn_on
      entity_id: scene.workday_terminate
