- platform: moon
- platform: uptime

- platform: season
  type: astronomical

- platform: filesize
  file_paths:
  - /config/home-assistant_v2.db

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free

- platform: time_date
  display_options:
  - "time"
  - "date"

- platform: random
  name: "flow_random_hue"
  minimum: 1
  maximum: 360

- platform: version
  name: "version_ha_current"

- platform: rest
  name: "computer_probe"
  resource: "http://192.168.1.101:8585"
  value_template: "{{value == ''}}"
  scan_interval: 300
- platform: rest
  name: "laptop_probe"
  resource: "http://192.168.1.102:8585"
  value_template: "{{value == ''}}"
  scan_interval: 300