- platform: moon
- platform: uptime

- platform: season
  type: astronomical

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: disk_use_percent
    arg: /home
  - type: swap_use_percent

- platform: command_line
  name: Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: GPU Temperature
  command: "/opt/vc/bin/vcgencmd measure_temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | replace("temp=", "") | replace("''C", "") | round(0) }}'

- platform: time_date
  display_options:
  - "time"
  - "date"

- platform: random
  name: flow_random_hue
  minimum: 1
  maximum: 360

- platform: version
  name: ha_version_current

- platform: rpi_power
  text_state: true

- platform: google_fit
  name: Google Fit
  client_id: !secret google_cal_int_client_id
  client_secret: !secret google_cal_int_client_secret