- platform: moon
- platform: uptime
- platform: version

- platform: season
  type: astronomical

- platform: filesize
  file_paths:
  - /config/home-assistant_v2.db

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free

- platform: time_date
  display_options:
  - "time"
  - "date"

- platform: random
  name: "flow_random_hue"
  minimum: 1
  maximum: 360