- platform: moon
- platform: uptime

#- platform: launch_library
#  name: launches

- platform: season
  type: astronomical

- platform: filesize
  file_paths:
  - /config/home-assistant_v2.db

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: disk_use_percent
    arg: /home
  - type: swap_use_percent

- platform: command_line
  name: "Temp"
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: time_date
  display_options:
  - "time"
  - "date"

- platform: random
  name: "flow_random_hue"
  minimum: 1
  maximum: 360

- platform: version
  name: "version_ha_current"

- platform: integration
  source: sensor.power_strip_1_load_power
  name: "power_strip_1_integral"
  unit_prefix: k
#- platform: integration
#  source: sensor.power_strip_1_load_power
#  name: "power_strip_1_integral_d"
#  unit_prefix: k
#  unit_time: d
#- platform: integration
#  source: sensor.power_strip_2_load_power
#  name: "power_strip_2_integration_h"
#  unit_prefix: k
#  unit_time: h
#- platform: integration
#  source: sensor.power_strip_2_load_power
#  name: "power_strip_2_integration_d"
#  unit_prefix: k
#  unit_time: d

