- platform: moon
- platform: uptime

- platform: season
  type: astronomical

- platform: filesize
  file_paths:
  - /config/home-assistant_v2.db

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: memory_use
  - type: memory_free

- platform: time_date
  display_options:
  - "time"
  - "date"

- platform: random
  name: "flow_random_hue"
  minimum: 1
  maximum: 360

- platform: version
  name: "version_ha_current"

- platform: rest
  resource: "http://192.168.1.101:8585"
  name: "bb_is_on"
  value_template: "{{value == ''}}"


#- platform: rest
#  resource: "https://s3.amazonaws.com/hassio-version/stable.json"
#  name: "version_ha_stable"
#  value_template: "{{value_json['homeassistant']['default']}}"
#
#- platform: rest
#  resource: "https://s3.amazonaws.com/hassio-version/beta.json"
#  name: "version_ha_beta"
#  value_template: "{{value_json['homeassistant']['default']}}"