- platform: derivative
  source: sensor.power_strip_1_load_power
  name: power_strip_1_derivative
  unit_prefix: k
  unit_time: h
  round: 4
- platform: derivative
  source: sensor.power_strip_2_load_power
  name: power_strip_2_derivative
  unit_prefix: k
  unit_time: h
  round: 4
- platform: derivative
  source: sensor.power_strip_3_load_power
  name: power_strip_3_derivative
  unit_prefix: k
  unit_time: h
  round: 4
- platform: derivative
  source: sensor.power_strip_4_load_power
  name: power_strip_4_derivative
  unit_prefix: k
  unit_time: h
  round: 4
- platform: derivative
  source: sensor.power_strip_5_load_power
  name: power_strip_5_derivative
  unit_prefix: k
  unit_time: h
  round: 4