- platform: derivative
  source: sensor.temperature_158d00022c7cf2
  name: park_temperature_derivative
- platform: derivative
  source: sensor.temperature_158d0002323783
  name: park_temperature_derivative