### IS_ON
- platform: history_stats
  name: computer_on_today
  entity_id: binary_sensor.ping_computer
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: laptop_on_today
  entity_id: binary_sensor.ping_laptop
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: tv_on_today
  entity_id: binary_sensor.ping_tv
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

### PH_ACTIVITY
- platform: history_stats
  name: dima_detected_activity_on_bicycle
  entity_id: sensor.sm_g973f_detected_activity
  type: "time"
  state: "on_bicycle"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: dima_detected_activity_in_vehicle
  entity_id: sensor.sm_g973f_detected_activity
  type: "time"
  state: "in_vehicle"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: dima_detected_activity_running
  entity_id: sensor.sm_g973f_detected_activity
  type: "time"
  state: "running"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: dima_detected_activity_walking
  entity_id: sensor.sm_g973f_detected_activity
  type: "time"
  state: "walking"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

### PH_INTERACTIVE
- platform: history_stats
  name: dima_interactive
  entity_id: binary_sensor.sm_g973f_interactive
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: yury_interactive
  entity_id: binary_sensor.redmi_note_9_pro_interactive
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: alyona_interactive
  entity_id: binary_sensor.mi_a2_interactive
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"
