- platform: history_stats
  name: computer_on_today
  entity_id: binary_sensor.ping_computer
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: laptop_on_today
  entity_id: binary_sensor.ping_laptop
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: tv_on_today
  entity_id: binary_sensor.ping_tv
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'