### TIMERS
- platform: history_stats
  name: computer_on_today
  entity_id: binary_sensor.ping_computer
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: laptop_on_today
  entity_id: binary_sensor.ping_laptop
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: tv_on_today
  entity_id: binary_sensor.ping_tv
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: androidbox_on_today
  entity_id: binary_sensor.ping_androidbox
  type: "time"
  state: "on"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: androidbox_play_today
  entity_id: media_player.androidbox
  type: "time"
  state: "playing"
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

### androidbox APPS
# - platform: history_stats
#   name: androidbox_youtube_today
#   entity_id: sensor.androidbox_app
#   type: "time"
#   state: "youtube"
#   start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
#   end: "{{ now() }}"

# - platform: history_stats
#   name: androidbox_perfectplayer_today
#   entity_id: sensor.androidbox_app
#   type: "time"
#   state: "pp"
#   start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
#   end: "{{ now() }}"

# - platform: history_stats
#   name: androidbox_launcher_today
#   entity_id: sensor.androidbox_app
#   type: "time"
#   state: "launcher"
#   start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
#   end: "{{ now() }}"

# - platform: history_stats
#   name: androidbox_hdvideo_today
#   entity_id: sensor.androidbox_app
#   type: "time"
#   state: "hdbox"
#   start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
#   end: "{{ now() }}"
