- platform: integration
  source: sensor.power_strip_1_load_power
  name: "power_strip_1_integral"
  unit_prefix: k
  unit_time: h
  round: 4
- platform: integration
  source: sensor.power_strip_2_load_power
  name: "power_strip_2_integral"
  unit_prefix: k
  unit_time: h
  round: 4
- platform: integration
  source: sensor.power_strip_3_load_power
  name: "power_strip_3_integral"
  unit_prefix: k
  unit_time: h
  round: 4
- platform: integration
  source: sensor.power_strip_4_load_power
  name: "power_strip_4_integral"
  unit_prefix: k
  unit_time: h
  round: 4
- platform: integration
  source: sensor.power_strip_5_load_power
  name: "power_strip_5_integral"
  unit_prefix: k
  unit_time: h
  round: 4

- platform: integration
  source: sensor.temperature_158d00022c7cf2
  name: "outside_temp_integral"
  round: 4
  
