#OUTDOOR COMPARERS
- platform: min_max
  type: min
  name: outdoor_temperature
  entity_ids:
    - sensor.0x00158d00022c7cf2_temperature
    - sensor.0x00158d0002323783_temperature

- platform: min_max
  type: max
  name: outdoor_humidity
  entity_ids:
    - sensor.0x00158d00022c7cf2_humidity
    - sensor.0x00158d0002323783_humidity

- platform: min_max
  type: max
  name: outdoor_pressure
  entity_ids:
    - sensor.0x00158d00022c7cf2_pressure
    - sensor.0x00158d0002323783_pressure

# #MIN/MAX WATCHERS
# - platform: min_max
#   type: min
#   name: outdoor_temperature_min
#   entity_ids:
#     - sensor.outdoor_temperature
#     - input_number.outdoor_temperature_min

# - platform: min_max
#   type: max
#   name: outdoor_temperature_max
#   entity_ids:
#     - sensor.outdoor_temperature
#     - input_number.outdoor_temperature_max