- platform: mqtt
  state_topic: "outside/temperature/min"
  name: outside_temperature_min
- platform: mqtt
  state_topic: "outside/temperature/max"
  name: outside_temperature_max
- platform: mqtt
  state_topic: "outside/temperature/diff"
  name: outside_temperature_diff

- platform: mqtt
  state_topic: "outside/temperature/min/at"
  name: outside_temperature_min_at
- platform: mqtt
  state_topic: "outside/temperature/max/at"
  name: outside_temperature_max_at

- platform: mqtt
  name: bridge_state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
