- platform: mqtt
  state_topic: "livingroom/motions"
  name: "livingroom_motions"
- platform: mqtt
  state_topic: "bathroom/motions"
  name: "bathroom_motions"
- platform: mqtt
  state_topic: "yuriroom/motions"
  name: "yuriroom_motions"

- platform: mqtt
  state_topic: "bathroom/motion"
  name: "bathroom_motion"
- platform: mqtt
  state_topic: "bathroom/switch"
  name: "bathroom_switch"
- platform: mqtt
  state_topic: "corridor/switch"
  name: "corridor_switch"
- platform: mqtt
  state_topic: "door/state"
  name: "door_state"
- platform: mqtt
  state_topic: "doorbell/state"
  name: "doorbell_state"
- platform: mqtt
  state_topic: "livingroom/motion"
  name: "livingroom_motion"

- platform: mqtt
  state_topic: "outside/temperature/min"
  name: "outside_temperature_min"
- platform: mqtt
  state_topic: "outside/temperature/max"
  name: "outside_temperature_max"
- platform: mqtt
  state_topic: "outside/temperature/diff"
  name: "outside_temperature_diff"

- platform: mqtt
  state_topic: "outside/temperature/min/at"
  name: "outside_temperature_min_at"
- platform: mqtt
  state_topic: "outside/temperature/max/at"
  name: "outside_temperature_max_at"

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless