- platform: mqtt
  state_topic: "power/computer/day"
  name: "power_computer_day"
- platform: mqtt
  state_topic: "power/computer/week"
  name: "power_computer_week"
- platform: mqtt
  state_topic: "power/computer/month"
  name: "power_computer_month"

- platform: mqtt
  state_topic: "power/kitchen/day"
  name: "power_kitchen_day"
- platform: mqtt
  state_topic: "power/kitchen/week"
  name: "power_kitchen_week"
- platform: mqtt
  state_topic: "power/kitchen/month"
  name: "power_kitchen_month"

- platform: mqtt
  state_topic: "power/router/day"
  name: "power_router_day"
- platform: mqtt
  state_topic: "power/router/week"
  name: "power_router_week"
- platform: mqtt
  state_topic: "power/router/month"
  name: "power_router_month"

- platform: mqtt
  state_topic: "power/tv/day"
  name: "power_tv_day"
- platform: mqtt
  state_topic: "power/tv/week"
  name: "power_tv_week"
- platform: mqtt
  state_topic: "power/tv/month"
  name: "power_tv_month"

- platform: mqtt
  state_topic: "power/fridge/day"
  name: "power_fridge_day"
- platform: mqtt
  state_topic: "power/fridge/week"
  name: "power_fridge_week"
- platform: mqtt
  state_topic: "power/fridge/month"
  name: "power_fridge_month"

- platform: mqtt
  state_topic: "livingroom/motions"
  name: "livingroom_motions"
- platform: mqtt
  state_topic: "bathroom/motions"
  name: "bathroom_motions"
- platform: mqtt
  state_topic: "yuriroom/motions"
  name: "yuriroom_motions"

- platform: mqtt
  state_topic: "bathroom/motion"
  name: "bathroom_motion"
- platform: mqtt
  state_topic: "bathroom/switch"
  name: "bathroom_switch"
- platform: mqtt
  state_topic: "corridor/switch"
  name: "corridor_switch"
- platform: mqtt
  state_topic: "door/state"
  name: "door_state"
- platform: mqtt
  state_topic: "doorbell/state"
  name: "doorbell_state"
- platform: mqtt
  state_topic: "livingroom/motion"
  name: "livingroom_motion"

- platform: mqtt
  state_topic: "outside/temperature/min"
  name: "outside_temperature_min"
- platform: mqtt
  state_topic: "outside/temperature/max"
  name: "outside_temperature_max"
- platform: mqtt
  state_topic: "outside/temperature/diff"
  name: "outside_temperature_diff"

- platform: mqtt
  state_topic: "outside/temperature/min/at"
  name: "outside_temperature_min_at"
- platform: mqtt
  state_topic: "outside/temperature/max/at"
  name: "outside_temperature_max_at"

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless