- platform: rest
  name: "cast_version_yuri_speaker"
  resource: http://192.168.1.30:8008/setup/eureka_info
  value_template: "{{ value_json.cast_build_revision }}"
  scan_interval: 86400

- platform: rest
  name: "cast_version_black_speaker"
  resource: http://192.168.1.34:8008/setup/eureka_info
  value_template: "{{ value_json.cast_build_revision }}"
  scan_interval: 86400

- platform: rest
  name: "cast_version_loud_speaker"
  resource: http://192.168.1.31:8008/setup/eureka_info
  value_template: "{{ value_json.cast_build_revision }}"
  scan_interval: 86400

- platform: rest
  name: "cast_version_kitchen_display"
  resource: http://192.168.1.32:8008/setup/eureka_info
  value_template: "{{ value_json.cast_build_revision }}"
  scan_interval: 86400

- platform: rest
  name: "cast_version_chromecast"
  resource: http://192.168.1.33:8008/setup/eureka_info
  value_template: "{{ value_json.cast_build_revision }}"
  scan_interval: 86400