- platform: moon
- platform: uptime

- platform: season
  type: astronomical

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: disk_use_percent
    arg: /home
  - type: swap_use_percent

- platform: command_line
  name: Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: time_date
  display_options:
  - time
  - date

- platform: version
  name: ha_version_current

- platform: filter
  name: "abox_temp_filtered"
  entity_id: sensor.abox_temp
  filters:
    - filter: lowpass
      time_constant: 10
      precision: 2