- platform: moon
- platform: uptime

- platform: season
  type: astronomical

- platform: systemmonitor
  resources:
  - type: processor_use
  - type: memory_use_percent
  - type: disk_use_percent
    arg: /home
  - type: swap_use_percent

- platform: command_line
  name: Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: time_date
  display_options:
  - time
  - date

- platform: version
  name: ha_version_current

#to find channel ID: https://www.youtube.com/feeds/videos.xml?user=

- platform: youtube
  channel_id: UCq7JZ8ATgQWeu6sDM1czjhg #SG
- platform: youtube
  channel_id: UC101o-vQ2iOj9vr00JUlyKw #vrlmv
- platform: youtube
  channel_id: UCFuBWNNWrvnW99mxDzAHdrw #hfa
- platform: youtube
  channel_id: UCsKiNBoIWLpIxU6vsAv3v3w #lbdv
- platform: youtube
  channel_id: UC9PBzalIcEQCsiIkq36PyUA #DF
- platform: youtube
  channel_id: UCvQXaJTjA3jRucTKN4CGiwg #Sbch