- platform: statistics
  entity_id: sensor.power_strip_1_load_power
  name: "power_strip_1"
  sampling_size: 1000
  max_age:
    minutes: 60
- platform: statistics
  entity_id: sensor.power_strip_2_load_power
  sampling_size: 1000
  name: "power_strip_2"
  max_age:
    minutes: 60
- platform: statistics
  entity_id: sensor.power_strip_3_load_power
  sampling_size: 1000
  name: "power_strip_3"
  max_age:
    minutes: 60
- platform: statistics
  entity_id: sensor.power_strip_4_load_power
  sampling_size: 1000
  name: "power_strip_4"
  max_age:
    minutes: 60
