- platform: ping
  name: "ping_computer"
  host: 192.168.1.101
  count: 2
  scan_interval: 30

- platform: ping
  name: "ping_laptop"
  host: 192.168.1.102
  count: 2
  scan_interval: 180

- platform: template
  sensors:
    is_workday_bin:
      value_template: "{{ now().weekday() >= 0 and now().weekday() <= 4 }}"
      entity_id: now.weekday

    ping_tv:
      value_template: "{{states.sensor.power_strip_4_load_power.state | float > 80}}"
      device_class: connectivity
      entity_id: sensor.power_strip_4_load_power

    people_home:
      value_template: >
        {{
        is_state('light.big_torch', 'on') or
        is_state('light.corner_lamp', 'on') or
        is_state('binary_sensor.ping_computer', 'on') or
        is_state('binary_sensor.ping_laptop', 'on') or
        is_state('binary_sensor.ping_tv', 'on') or
        is_state('media_player.kitchen_display', 'playing') or
        is_state('media_player.loud_speaker', 'playing') or
        is_state('media_player.yury_speaker', 'playing')
        }}
      entity_id:
        - light.big_torch
        - light.corner_lamp
        - binary_sensor.ping_computer
        - binary_sensor.ping_laptop
        - binary_sensor.ping_tv
        - media_player.kitchen_display
        - media_player.loud_speaker
        - media_player.yury_speaker

    chromecast_is_active:
      value_template: >
        {{
        is_state('media_player.chromecast', 'playing') or
        is_state('media_player.chromecast', 'paused')
        }}
      entity_id: media_player.chromecast

    abox_is_active:
      value_template: >
        {{
        not(
        is_state('sensor.abox_app', 'launcher') or
        is_state('sensor.abox_app', 'unknown')
        )
        }}
      entity_id:
        - sensor.abox_app
        - media_player.abox