- platform: ping
  name: "ping_computer"
  host: 192.168.1.101
  scan_interval: 30
- platform: ping
  name: "ping_laptop"
  host: 192.168.1.102
  scan_interval: 90
#- platform: ping
#  name: "ping_android_box_wifi"
#  host: 192.168.1.20
#  scan_interval: 120
#- platform: ping
#  name: "ping_google_home"
#  host: 192.168.1.31
#  scan_interval: 120
#- platform: ping
#  name: "ping_google_home_mini"
#  host: 192.168.1.30
#  scan_interval: 120
#- platform: ping
#  name: "ping_yeelight_torch"
#  host: 192.168.1.131
#  scan_interval: 120
#- platform: ping
#  name: "ping_yeelight_corner"
#  host: 192.168.1.132
#  scan_interval: 120
#- platform: ping
#  name: "ping_yeelight_small_torch"
#  host: 192.168.1.133
#  scan_interval: 120
