- platform: template
  name: "computer_is_on"
  value_template: "{{states.sensor.computer_probe.state == 'True'}}"
- platform: template
  name: "laptop_is_on"
  value_template: "{{states.sensor.laptop_probe.state == 'True'}}"
