- platform: yeelight
  devices:
    192.168.1.131:
      name: big_torch
      transition: 500
      use_music_mode: True
    192.168.1.132:
      name: corner_lamp
      transition: 500
      use_music_mode: True
    192.168.1.133:
      name: small_torch
      transition: 400
      use_music_mode: True

- platform: mqtt
  name: garland
  state_topic: "stat/sonoff_garland/POWER"
  command_topic: "cmnd/sonoff_garland/POWER"
  availability_topic: "tele/sonoff_garland/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: fire_lamp
  state_topic: "stat/sonoff_firelamp/POWER"
  command_topic: "cmnd/sonoff_firelamp/POWER"
  availability_topic: "tele/sonoff_firelamp/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: window_stars
  state_topic: "stat/sonoff_window_stars/POWER"
  command_topic: "cmnd/sonoff_window_stars/POWER"
  availability_topic: "tele/sonoff_window_stars/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: group_livroom_ambient
  entities:
  - light.big_torch
  - light.corner_lamp

- platform: group
  name: group_christmas
  entities:
  - light.tree_lamp
  - light.window_stars

- platform: switch
  name: tree_lamp
  entity_id: switch.wall_plug_158d0002013f1e
- platform: switch
  name: corridor
  entity_id: switch.wall_switch_left_158d00022391ec
- platform: switch
  name: bathroom
  entity_id: switch.wall_switch_right_158d00022391ec
