- platform: yeelight
  devices:
    192.168.1.131:
      name: torch_giraffe
      transition: 1000
      use_music_mode: True
    192.168.1.132:
      name: corner_cat
      transition: 1000
      use_music_mode: True
    192.168.1.133:
      name: torch_jellyfish
      transition: 1000
      use_music_mode: True

- platform: mqtt
  name: garland_snake
  state_topic: "stat/sonoff_garland/POWER"
  command_topic: "cmnd/sonoff_garland/POWER"
  availability_topic: "tele/sonoff_garland/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: fire_fox
  state_topic: "stat/sonoff_firelamp/POWER"
  command_topic: "cmnd/sonoff_firelamp/POWER"
  availability_topic: "tele/sonoff_firelamp/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: livroom_ambient
  entities:
  - light.torch_giraffe
  - light.corner_cat

- platform: group
  name: morning
  entities:
  - light.torch_giraffe
  - light.corner_cat
  - light.fire_fox
  - light.torch_jellyfish
  - light.garland_snake

