- platform: yeelight
  devices:
    192.168.1.131:
      name: livingroom_torch
      transition: 1000
      use_music_mode: True
    192.168.1.132:
      name: livingroom_corner
      transition: 1000
      use_music_mode: True
    192.168.1.133:
      name: small_torch
      transition: 1000
      use_music_mode: True

- platform: group
  name: livingroom_ambient
  entities:
  - light.livingroom_torch
  - light.livingroom_corner

- platform: group
  name: livingroom
  entities:
  - light.livingroom_ambient
  - light.gateway_light_7811dcb36cee

- platform: mqtt
  name: entrance_garland
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/POWER"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false