- platform: yeelight
  devices:
    192.168.1.131:
      name: livingroom_torch
      transition: 1000
      use_music_mode: True
    192.168.1.132:
      name: livingroom_corner
      transition: 1000
      use_music_mode: True
    192.168.1.133:
      name: small_torch
      transition: 1000
      use_music_mode: True

- platform: mqtt
  name: garland
  state_topic: "stat/sonoff_garland/POWER"
  command_topic: "cmnd/sonoff_garland/POWER"
  availability_topic: "tele/sonoff_garland/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: firelamp
  state_topic: "stat/sonoff_firelamp/POWER"
  command_topic: "cmnd/sonoff_firelamp/POWER"
  availability_topic: "tele/sonoff_firelamp/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: livroom_ambient
  entities:
  - light.livingroom_torch
  - light.livingroom_corner

- platform: group
  name: morning
  entities:
  - light.livingroom_torch
  - light.livingroom_corner
  - light.small_torch
  - light.garland

- platform: group
  name: morning_core
  entities:
  - light.livingroom_torch
  - light.livingroom_corner
  - light.garland

