- platform: yeelight
  devices:
    192.168.1.131:
      name: big_torch
      transition: 1000
      use_music_mode: True
    192.168.1.132:
      name: corner_lamp
      transition: 1000
      use_music_mode: True
    192.168.1.133:
      name: small_torch
      transition: 1000
      use_music_mode: True

- platform: mqtt
  name: garland
  state_topic: "stat/sonoff_garland/POWER"
  command_topic: "cmnd/sonoff_garland/POWER"
  availability_topic: "tele/sonoff_garland/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: fire_lamp
  state_topic: "stat/sonoff_firelamp/POWER"
  command_topic: "cmnd/sonoff_firelamp/POWER"
  availability_topic: "tele/sonoff_firelamp/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: livroom_ambient
  entities:
  - light.big_torch
  - light.corner_lamp

- platform: group
  name: morning
  entities:
  - light.livroom_ambient
  - light.garland
  - light.fire_lamp

