- platform: mqtt
  name: window_stars
  state_topic: "stat/sonoff_window_stars/POWER"
  command_topic: "cmnd/sonoff_window_stars/POWER"
  availability_topic: "tele/sonoff_window_stars/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: hallway_ceiling
  entities:
  - light.0xec1bbdfffe4d16eb_light
  - light.0xec1bbdfffe18a191_light

- platform: group
  name: hallway
  entities:
  - light.hallway_ceiling
  - light.fire_lamp
  - light.garland

- platform: group
  name: livingroom
  entities:
  - light.livingroom_adjustable
  - light.standalone_switch

- platform: group
  name: livingroom_adjustable
  entities:
  - light.big_torch
  - light.corner_lamp

- platform: group
  name: christmas
  entities:
  - light.tree_lamp
  - light.window_stars

- platform: switch
  name: standalone_switch
  entity_id: switch.0x00158d0002013f1e_switch
- platform: switch
  name: corridor
  entity_id: switch.0x00158d00022391ec_switch_left
- platform: switch
  name: bathroom
  entity_id: switch.0x00158d00022391ec_switch_right