- platform: mqtt
  name: garland
  state_topic: "stat/sonoff_garland/POWER"
  command_topic: "cmnd/sonoff_garland/POWER"
  availability_topic: "tele/sonoff_garland/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: fire_lamp
  state_topic: "stat/sonoff_firelamp/POWER"
  command_topic: "cmnd/sonoff_firelamp/POWER"
  availability_topic: "tele/sonoff_firelamp/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: window_stars
  state_topic: "stat/sonoff_window_stars/POWER"
  command_topic: "cmnd/sonoff_window_stars/POWER"
  availability_topic: "tele/sonoff_window_stars/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: group
  name: livingroom
  entities:
  - light.big_torch
  - light.corner_lamp

- platform: group
  name: christmas
  entities:
  - light.tree_lamp
  - light.window_stars

- platform: switch
  name: standalone_switch
  entity_id: switch.wall_plug_158d0002013f1e
- platform: switch
  name: corridor
  entity_id: switch.wall_switch_left_158d00022391ec
- platform: switch
  name: bathroom
  entity_id: switch.wall_switch_right_158d00022391ec
