# - platform: spotify
#   client_id: !secret spotify_client_id
#   client_secret: !secret spotify_client_secret

- platform: androidtv
  host: 192.168.1.20
  name: androidbox
  device_class: androidtv
  adb_server_ip: 127.0.0.1
  adb_server_port: 5037
  apps:
    com.google.android.youtube: "Youtube"
    com.google.android.apps.youtube.music: "Youtube Music"
    com.teslacoilsw.launcher: "Nova"
    com.niklabs.pp: "PerfectPlayer"
    dkc.video.hdbox: "HDVideobox"
